
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.1.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner;

import java.time.LocalDateTime;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.CreditWorthinessField;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable.CreditWorthinessSelectable;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * Credit Worthiness<p></p><p>Original entity name from the Odata EDM: <b>A_BPCreditWorthinessType</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class CreditWorthiness
    extends VdmEntity<CreditWorthiness>
{

    /**
     * Selector for all available fields of CreditWorthiness.
     * 
     */
    public final static CreditWorthinessSelectable ALL_FIELDS = () -> "*";
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>BusinessPartner</b></p>
     * 
     * @return
     *     Business Partner Number
     */
    @Key
    @SerializedName("BusinessPartner")
    @JsonProperty("BusinessPartner")
    @Nullable
    @ODataField(odataName = "BusinessPartner")
    private String businessPartner;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartner</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<String> BUSINESS_PARTNER = new CreditWorthinessField<String>("BusinessPartner");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BusPartCreditStanding</b></p>
     * 
     * @return
     *     Credit Standing
     */
    @SerializedName("BusPartCreditStanding")
    @JsonProperty("BusPartCreditStanding")
    @Nullable
    @ODataField(odataName = "BusPartCreditStanding")
    private String creditStanding;
    /**
     * Use with available fluent helpers to apply the <b>BusPartCreditStanding</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<String> CREDIT_STANDING = new CreditWorthinessField<String>("BusPartCreditStanding");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPCreditStandingStatus</b></p>
     * 
     * @return
     *     Status of Credit Standing Information
     */
    @SerializedName("BPCreditStandingStatus")
    @JsonProperty("BPCreditStandingStatus")
    @Nullable
    @ODataField(odataName = "BPCreditStandingStatus")
    private String statCredStndgInfo;
    /**
     * Use with available fluent helpers to apply the <b>BPCreditStandingStatus</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<String> STAT_CRED_STNDG_INFO = new CreditWorthinessField<String>("BPCreditStandingStatus");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>CreditRatingAgency</b></p>
     * 
     * @return
     *     Institute Providing Credit Standing Information
     */
    @SerializedName("CreditRatingAgency")
    @JsonProperty("CreditRatingAgency")
    @Nullable
    @ODataField(odataName = "CreditRatingAgency")
    private String credStndgInst;
    /**
     * Use with available fluent helpers to apply the <b>CreditRatingAgency</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<String> CRED_STNDG_INST = new CreditWorthinessField<String>("CreditRatingAgency");
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>BPCreditStandingComment</b></p>
     * 
     * @return
     *     Additional Credit Standing Information
     */
    @SerializedName("BPCreditStandingComment")
    @JsonProperty("BPCreditStandingComment")
    @Nullable
    @ODataField(odataName = "BPCreditStandingComment")
    private String creditStandingText;
    /**
     * Use with available fluent helpers to apply the <b>BPCreditStandingComment</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<String> CREDIT_STANDING_TEXT = new CreditWorthinessField<String>("BPCreditStandingComment");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPCreditStandingDate</b></p>
     * 
     * @return
     *     Date of Credit Standing Information
     */
    @SerializedName("BPCreditStandingDate")
    @JsonProperty("BPCreditStandingDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPCreditStandingDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime dtCredStndgInfo;
    /**
     * Use with available fluent helpers to apply the <b>BPCreditStandingDate</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<LocalDateTime> DT_CRED_STNDG_INFO = new CreditWorthinessField<LocalDateTime>("BPCreditStandingDate");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>BPCreditStandingRating</b></p>
     * 
     * @return
     *     Rating
     */
    @SerializedName("BPCreditStandingRating")
    @JsonProperty("BPCreditStandingRating")
    @Nullable
    @ODataField(odataName = "BPCreditStandingRating")
    private String rating;
    /**
     * Use with available fluent helpers to apply the <b>BPCreditStandingRating</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<String> RATING = new CreditWorthinessField<String>("BPCreditStandingRating");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BPLegalProceedingStatus</b></p>
     * 
     * @return
     *     Status of Legal Proceedings
     */
    @SerializedName("BPLegalProceedingStatus")
    @JsonProperty("BPLegalProceedingStatus")
    @Nullable
    @ODataField(odataName = "BPLegalProceedingStatus")
    private String statusOfLegProc;
    /**
     * Use with available fluent helpers to apply the <b>BPLegalProceedingStatus</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<String> STATUS_OF_LEG_PROC = new CreditWorthinessField<String>("BPLegalProceedingStatus");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPLglProceedingInitiationDate</b></p>
     * 
     * @return
     *     Date of Initiation of Legal Proceedings
     */
    @SerializedName("BPLglProceedingInitiationDate")
    @JsonProperty("BPLglProceedingInitiationDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPLglProceedingInitiationDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime dateOfLegalProc;
    /**
     * Use with available fluent helpers to apply the <b>BPLglProceedingInitiationDate</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<LocalDateTime> DATE_OF_LEGAL_PROC = new CreditWorthinessField<LocalDateTime>("BPLglProceedingInitiationDate");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BusinessPartnerIsUnderOath</b></p>
     * 
     * @return
     *     Affidavit
     */
    @SerializedName("BusinessPartnerIsUnderOath")
    @JsonProperty("BusinessPartnerIsUnderOath")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BusinessPartnerIsUnderOath")
    private Boolean affidavit;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerIsUnderOath</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<Boolean> AFFIDAVIT = new CreditWorthinessField<Boolean>("BusinessPartnerIsUnderOath");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BusinessPartnerOathDate</b></p>
     * 
     * @return
     *     Date of affidavit
     */
    @SerializedName("BusinessPartnerOathDate")
    @JsonProperty("BusinessPartnerOathDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BusinessPartnerOathDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime dateOfAffidavit;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerOathDate</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<LocalDateTime> DATE_OF_AFFIDAVIT = new CreditWorthinessField<LocalDateTime>("BusinessPartnerOathDate");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BusinessPartnerIsBankrupt</b></p>
     * 
     * @return
     *     Launch Bankruptcy Proceedings
     */
    @SerializedName("BusinessPartnerIsBankrupt")
    @JsonProperty("BusinessPartnerIsBankrupt")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BusinessPartnerIsBankrupt")
    private Boolean bankruptcyProceed;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerIsBankrupt</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<Boolean> BANKRUPTCY_PROCEED = new CreditWorthinessField<Boolean>("BusinessPartnerIsBankrupt");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BusinessPartnerBankruptcyDate</b></p>
     * 
     * @return
     *     Commencement Date of Bankruptcy Proceedings
     */
    @SerializedName("BusinessPartnerBankruptcyDate")
    @JsonProperty("BusinessPartnerBankruptcyDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BusinessPartnerBankruptcyDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime bankruptcyPrDate;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerBankruptcyDate</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<LocalDateTime> BANKRUPTCY_PR_DATE = new CreditWorthinessField<LocalDateTime>("BusinessPartnerBankruptcyDate");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPForeclosureIsInitiated</b></p>
     * 
     * @return
     *     Foreclosure
     */
    @SerializedName("BPForeclosureIsInitiated")
    @JsonProperty("BPForeclosureIsInitiated")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BPForeclosureIsInitiated")
    private Boolean foreclosure;
    /**
     * Use with available fluent helpers to apply the <b>BPForeclosureIsInitiated</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<Boolean> FORECLOSURE = new CreditWorthinessField<Boolean>("BPForeclosureIsInitiated");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPForeclosureDate</b></p>
     * 
     * @return
     *     Date of foreclosure
     */
    @SerializedName("BPForeclosureDate")
    @JsonProperty("BPForeclosureDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPForeclosureDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime dateOfForeclosure;
    /**
     * Use with available fluent helpers to apply the <b>BPForeclosureDate</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<LocalDateTime> DATE_OF_FORECLOSURE = new CreditWorthinessField<LocalDateTime>("BPForeclosureDate");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPCrdtWrthnssAccessChkIsActive</b></p>
     * 
     * @return
     *     The bPCrdtWrthnssAccessChkIsActive contained in this entity.
     */
    @SerializedName("BPCrdtWrthnssAccessChkIsActive")
    @JsonProperty("BPCrdtWrthnssAccessChkIsActive")
    @Nullable
    @ODataField(odataName = "BPCrdtWrthnssAccessChkIsActive")
    private String bPCrdtWrthnssAccessChkIsActive;
    /**
     * Use with available fluent helpers to apply the <b>BPCrdtWrthnssAccessChkIsActive</b> field to query operations.
     * 
     */
    public final static CreditWorthinessField<String> BP_CRDT_WRTHNSS_ACCESS_CHK_IS_ACTIVE = new CreditWorthinessField<String>("BPCrdtWrthnssAccessChkIsActive");

    @Nonnull
    @Override
    public Class<CreditWorthiness> getType() {
        return CreditWorthiness.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>BusinessPartner</b></p>
     * 
     * @param businessPartner
     *     Business Partner Number
     */
    public void setBusinessPartner(
        @Nullable
        final String businessPartner) {
        rememberChangedField("BusinessPartner", this.businessPartner);
        this.businessPartner = businessPartner;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BusPartCreditStanding</b></p>
     * 
     * @param creditStanding
     *     Credit Standing
     */
    public void setCreditStanding(
        @Nullable
        final String creditStanding) {
        rememberChangedField("BusPartCreditStanding", this.creditStanding);
        this.creditStanding = creditStanding;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPCreditStandingStatus</b></p>
     * 
     * @param statCredStndgInfo
     *     Status of Credit Standing Information
     */
    public void setStatCredStndgInfo(
        @Nullable
        final String statCredStndgInfo) {
        rememberChangedField("BPCreditStandingStatus", this.statCredStndgInfo);
        this.statCredStndgInfo = statCredStndgInfo;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>CreditRatingAgency</b></p>
     * 
     * @param credStndgInst
     *     Institute Providing Credit Standing Information
     */
    public void setCredStndgInst(
        @Nullable
        final String credStndgInst) {
        rememberChangedField("CreditRatingAgency", this.credStndgInst);
        this.credStndgInst = credStndgInst;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>BPCreditStandingComment</b></p>
     * 
     * @param creditStandingText
     *     Additional Credit Standing Information
     */
    public void setCreditStandingText(
        @Nullable
        final String creditStandingText) {
        rememberChangedField("BPCreditStandingComment", this.creditStandingText);
        this.creditStandingText = creditStandingText;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPCreditStandingDate</b></p>
     * 
     * @param dtCredStndgInfo
     *     Date of Credit Standing Information
     */
    public void setDtCredStndgInfo(
        @Nullable
        final LocalDateTime dtCredStndgInfo) {
        rememberChangedField("BPCreditStandingDate", this.dtCredStndgInfo);
        this.dtCredStndgInfo = dtCredStndgInfo;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>BPCreditStandingRating</b></p>
     * 
     * @param rating
     *     Rating
     */
    public void setRating(
        @Nullable
        final String rating) {
        rememberChangedField("BPCreditStandingRating", this.rating);
        this.rating = rating;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BPLegalProceedingStatus</b></p>
     * 
     * @param statusOfLegProc
     *     Status of Legal Proceedings
     */
    public void setStatusOfLegProc(
        @Nullable
        final String statusOfLegProc) {
        rememberChangedField("BPLegalProceedingStatus", this.statusOfLegProc);
        this.statusOfLegProc = statusOfLegProc;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPLglProceedingInitiationDate</b></p>
     * 
     * @param dateOfLegalProc
     *     Date of Initiation of Legal Proceedings
     */
    public void setDateOfLegalProc(
        @Nullable
        final LocalDateTime dateOfLegalProc) {
        rememberChangedField("BPLglProceedingInitiationDate", this.dateOfLegalProc);
        this.dateOfLegalProc = dateOfLegalProc;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BusinessPartnerIsUnderOath</b></p>
     * 
     * @param affidavit
     *     Affidavit
     */
    public void setAffidavit(
        @Nullable
        final Boolean affidavit) {
        rememberChangedField("BusinessPartnerIsUnderOath", this.affidavit);
        this.affidavit = affidavit;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BusinessPartnerOathDate</b></p>
     * 
     * @param dateOfAffidavit
     *     Date of affidavit
     */
    public void setDateOfAffidavit(
        @Nullable
        final LocalDateTime dateOfAffidavit) {
        rememberChangedField("BusinessPartnerOathDate", this.dateOfAffidavit);
        this.dateOfAffidavit = dateOfAffidavit;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BusinessPartnerIsBankrupt</b></p>
     * 
     * @param bankruptcyProceed
     *     Launch Bankruptcy Proceedings
     */
    public void setBankruptcyProceed(
        @Nullable
        final Boolean bankruptcyProceed) {
        rememberChangedField("BusinessPartnerIsBankrupt", this.bankruptcyProceed);
        this.bankruptcyProceed = bankruptcyProceed;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BusinessPartnerBankruptcyDate</b></p>
     * 
     * @param bankruptcyPrDate
     *     Commencement Date of Bankruptcy Proceedings
     */
    public void setBankruptcyPrDate(
        @Nullable
        final LocalDateTime bankruptcyPrDate) {
        rememberChangedField("BusinessPartnerBankruptcyDate", this.bankruptcyPrDate);
        this.bankruptcyPrDate = bankruptcyPrDate;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPForeclosureIsInitiated</b></p>
     * 
     * @param foreclosure
     *     Foreclosure
     */
    public void setForeclosure(
        @Nullable
        final Boolean foreclosure) {
        rememberChangedField("BPForeclosureIsInitiated", this.foreclosure);
        this.foreclosure = foreclosure;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPForeclosureDate</b></p>
     * 
     * @param dateOfForeclosure
     *     Date of foreclosure
     */
    public void setDateOfForeclosure(
        @Nullable
        final LocalDateTime dateOfForeclosure) {
        rememberChangedField("BPForeclosureDate", this.dateOfForeclosure);
        this.dateOfForeclosure = dateOfForeclosure;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPCrdtWrthnssAccessChkIsActive</b></p>
     * 
     * @param bPCrdtWrthnssAccessChkIsActive
     *     The bPCrdtWrthnssAccessChkIsActive to set.
     */
    public void setBPCrdtWrthnssAccessChkIsActive(
        @Nullable
        final String bPCrdtWrthnssAccessChkIsActive) {
        rememberChangedField("BPCrdtWrthnssAccessChkIsActive", this.bPCrdtWrthnssAccessChkIsActive);
        this.bPCrdtWrthnssAccessChkIsActive = bPCrdtWrthnssAccessChkIsActive;
    }

    @Override
    protected String getEntityCollection() {
        return "A_BPCreditWorthiness";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("BusinessPartner", getBusinessPartner());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("BusinessPartner", getBusinessPartner());
        values.put("BusPartCreditStanding", getCreditStanding());
        values.put("BPCreditStandingStatus", getStatCredStndgInfo());
        values.put("CreditRatingAgency", getCredStndgInst());
        values.put("BPCreditStandingComment", getCreditStandingText());
        values.put("BPCreditStandingDate", getDtCredStndgInfo());
        values.put("BPCreditStandingRating", getRating());
        values.put("BPLegalProceedingStatus", getStatusOfLegProc());
        values.put("BPLglProceedingInitiationDate", getDateOfLegalProc());
        values.put("BusinessPartnerIsUnderOath", getAffidavit());
        values.put("BusinessPartnerOathDate", getDateOfAffidavit());
        values.put("BusinessPartnerIsBankrupt", getBankruptcyProceed());
        values.put("BusinessPartnerBankruptcyDate", getBankruptcyPrDate());
        values.put("BPForeclosureIsInitiated", getForeclosure());
        values.put("BPForeclosureDate", getDateOfForeclosure());
        values.put("BPCrdtWrthnssAccessChkIsActive", getBPCrdtWrthnssAccessChkIsActive());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("BusinessPartner")) {
                final Object value = values.remove("BusinessPartner");
                if ((value == null)||(!value.equals(getBusinessPartner()))) {
                    setBusinessPartner(((String) value));
                }
            }
            if (values.containsKey("BusPartCreditStanding")) {
                final Object value = values.remove("BusPartCreditStanding");
                if ((value == null)||(!value.equals(getCreditStanding()))) {
                    setCreditStanding(((String) value));
                }
            }
            if (values.containsKey("BPCreditStandingStatus")) {
                final Object value = values.remove("BPCreditStandingStatus");
                if ((value == null)||(!value.equals(getStatCredStndgInfo()))) {
                    setStatCredStndgInfo(((String) value));
                }
            }
            if (values.containsKey("CreditRatingAgency")) {
                final Object value = values.remove("CreditRatingAgency");
                if ((value == null)||(!value.equals(getCredStndgInst()))) {
                    setCredStndgInst(((String) value));
                }
            }
            if (values.containsKey("BPCreditStandingComment")) {
                final Object value = values.remove("BPCreditStandingComment");
                if ((value == null)||(!value.equals(getCreditStandingText()))) {
                    setCreditStandingText(((String) value));
                }
            }
            if (values.containsKey("BPCreditStandingDate")) {
                final Object value = values.remove("BPCreditStandingDate");
                if ((value == null)||(!value.equals(getDtCredStndgInfo()))) {
                    setDtCredStndgInfo(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BPCreditStandingRating")) {
                final Object value = values.remove("BPCreditStandingRating");
                if ((value == null)||(!value.equals(getRating()))) {
                    setRating(((String) value));
                }
            }
            if (values.containsKey("BPLegalProceedingStatus")) {
                final Object value = values.remove("BPLegalProceedingStatus");
                if ((value == null)||(!value.equals(getStatusOfLegProc()))) {
                    setStatusOfLegProc(((String) value));
                }
            }
            if (values.containsKey("BPLglProceedingInitiationDate")) {
                final Object value = values.remove("BPLglProceedingInitiationDate");
                if ((value == null)||(!value.equals(getDateOfLegalProc()))) {
                    setDateOfLegalProc(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BusinessPartnerIsUnderOath")) {
                final Object value = values.remove("BusinessPartnerIsUnderOath");
                if ((value == null)||(!value.equals(getAffidavit()))) {
                    setAffidavit(((Boolean) value));
                }
            }
            if (values.containsKey("BusinessPartnerOathDate")) {
                final Object value = values.remove("BusinessPartnerOathDate");
                if ((value == null)||(!value.equals(getDateOfAffidavit()))) {
                    setDateOfAffidavit(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BusinessPartnerIsBankrupt")) {
                final Object value = values.remove("BusinessPartnerIsBankrupt");
                if ((value == null)||(!value.equals(getBankruptcyProceed()))) {
                    setBankruptcyProceed(((Boolean) value));
                }
            }
            if (values.containsKey("BusinessPartnerBankruptcyDate")) {
                final Object value = values.remove("BusinessPartnerBankruptcyDate");
                if ((value == null)||(!value.equals(getBankruptcyPrDate()))) {
                    setBankruptcyPrDate(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BPForeclosureIsInitiated")) {
                final Object value = values.remove("BPForeclosureIsInitiated");
                if ((value == null)||(!value.equals(getForeclosure()))) {
                    setForeclosure(((Boolean) value));
                }
            }
            if (values.containsKey("BPForeclosureDate")) {
                final Object value = values.remove("BPForeclosureDate");
                if ((value == null)||(!value.equals(getDateOfForeclosure()))) {
                    setDateOfForeclosure(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BPCrdtWrthnssAccessChkIsActive")) {
                final Object value = values.remove("BPCrdtWrthnssAccessChkIsActive");
                if ((value == null)||(!value.equals(getBPCrdtWrthnssAccessChkIsActive()))) {
                    setBPCrdtWrthnssAccessChkIsActive(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >CreditWorthinessField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new CreditWorthinessField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >CreditWorthinessField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new CreditWorthinessField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public Destination getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final Destination destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return (com.sap.cloud.sdk.tutorial.datamodel.odata.services.BusinessPartnerService.DEFAULT_SERVICE_PATH);
    }

}
