
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.1.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperByKey;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable.CustomerUnloadingPointSelectable;


/**
 * Fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerUnloadingPoint CustomerUnloadingPoint} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class CustomerUnloadingPointByKeyFluentHelper
    extends FluentHelperByKey<CustomerUnloadingPointByKeyFluentHelper, CustomerUnloadingPoint, CustomerUnloadingPointSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerUnloadingPoint CustomerUnloadingPoint} entity with the provided key field values. To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
     * 
     * @param entityCollection
     *     Entity Collection to be used to fetch a single {@code CustomerUnloadingPoint}
     * @param unloadingPoint
     *     Unloading Point<p>Constraints: Not nullable, Maximum length: 25</p>
     * @param servicePath
     *     Service path to be used to fetch a single {@code CustomerUnloadingPoint}
     * @param customer
     *     Customer Number<p>Constraints: Not nullable, Maximum length: 10</p>
     */
    public CustomerUnloadingPointByKeyFluentHelper(
        @Nonnull
        final String servicePath,
        @Nonnull
        final String entityCollection, final String customer, final String unloadingPoint) {
        super(servicePath, entityCollection);
        this.key.put("Customer", customer);
        this.key.put("UnloadingPointName", unloadingPoint);
    }

    @Override
    @Nonnull
    protected Class<CustomerUnloadingPoint> getEntityClass() {
        return CustomerUnloadingPoint.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
