
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.1.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner;

import java.time.LocalDateTime;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.FinancialServicesReportingField;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable.FinancialServicesReportingSelectable;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * Financial Services Reporting<p></p><p>Original entity name from the Odata EDM: <b>A_BPFinancialServicesReportingType</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class FinancialServicesReporting
    extends VdmEntity<FinancialServicesReporting>
{

    /**
     * Selector for all available fields of FinancialServicesReporting.
     * 
     */
    public final static FinancialServicesReportingSelectable ALL_FIELDS = () -> "*";
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>BusinessPartner</b></p>
     * 
     * @return
     *     Business Partner Number
     */
    @Key
    @SerializedName("BusinessPartner")
    @JsonProperty("BusinessPartner")
    @Nullable
    @ODataField(odataName = "BusinessPartner")
    private String businessPartner;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartner</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> BUSINESS_PARTNER = new FinancialServicesReportingField<String>("BusinessPartner");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPIsNonResident</b></p>
     * 
     * @return
     *     Non-Resident According to Paragraph 4 AWG
     */
    @SerializedName("BPIsNonResident")
    @JsonProperty("BPIsNonResident")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BPIsNonResident")
    private Boolean nonResident;
    /**
     * Use with available fluent helpers to apply the <b>BPIsNonResident</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<Boolean> NON_RESIDENT = new FinancialServicesReportingField<Boolean>("BPIsNonResident");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPNonResidencyStartDate</b></p>
     * 
     * @return
     *     Start of Non-Residency According to Paragraph 4 AWG
     */
    @SerializedName("BPNonResidencyStartDate")
    @JsonProperty("BPNonResidencyStartDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPNonResidencyStartDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime nonResidentSince;
    /**
     * Use with available fluent helpers to apply the <b>BPNonResidencyStartDate</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<LocalDateTime> NON_RESIDENT_SINCE = new FinancialServicesReportingField<LocalDateTime>("BPNonResidencyStartDate");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPIsMultimillionLoanRecipient</b></p>
     * 
     * @return
     *     Recipient of Multimillion Loan According to Paragraph 14 GBA
     */
    @SerializedName("BPIsMultimillionLoanRecipient")
    @JsonProperty("BPIsMultimillionLoanRecipient")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BPIsMultimillionLoanRecipient")
    private Boolean multimillionLoan;
    /**
     * Use with available fluent helpers to apply the <b>BPIsMultimillionLoanRecipient</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<Boolean> MULTIMILLION_LOAN = new FinancialServicesReportingField<Boolean>("BPIsMultimillionLoanRecipient");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>BPLoanReportingBorrowerNumber</b></p>
     * 
     * @return
     *     Borrower Number for Reporting a Loan According to GBA
     */
    @SerializedName("BPLoanReportingBorrowerNumber")
    @JsonProperty("BPLoanReportingBorrowerNumber")
    @Nullable
    @ODataField(odataName = "BPLoanReportingBorrowerNumber")
    private String borrowerNumber;
    /**
     * Use with available fluent helpers to apply the <b>BPLoanReportingBorrowerNumber</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> BORROWER_NUMBER = new FinancialServicesReportingField<String>("BPLoanReportingBorrowerNumber");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>BPLoanRptgBorrowerEntityNumber</b></p>
     * 
     * @return
     *     Borrower Entity Number Used to Report Loan acc. to GBA
     */
    @SerializedName("BPLoanRptgBorrowerEntityNumber")
    @JsonProperty("BPLoanRptgBorrowerEntityNumber")
    @Nullable
    @ODataField(odataName = "BPLoanRptgBorrowerEntityNumber")
    private String borrEntityNo;
    /**
     * Use with available fluent helpers to apply the <b>BPLoanRptgBorrowerEntityNumber</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> BORR_ENTITY_NO = new FinancialServicesReportingField<String>("BPLoanRptgBorrowerEntityNumber");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BPCreditStandingReview</b></p>
     * 
     * @return
     *     Credit Standing Review According to Paragraph 18 GBA
     */
    @SerializedName("BPCreditStandingReview")
    @JsonProperty("BPCreditStandingReview")
    @Nullable
    @ODataField(odataName = "BPCreditStandingReview")
    private String gBAInformation;
    /**
     * Use with available fluent helpers to apply the <b>BPCreditStandingReview</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> GBA_INFORMATION = new FinancialServicesReportingField<String>("BPCreditStandingReview");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPCreditStandingReviewDate</b></p>
     * 
     * @return
     *     Date of Credit Standing Review According to Paragraph 18 GBA
     */
    @SerializedName("BPCreditStandingReviewDate")
    @JsonProperty("BPCreditStandingReviewDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPCreditStandingReviewDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime credStandRevDat;
    /**
     * Use with available fluent helpers to apply the <b>BPCreditStandingReviewDate</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<LocalDateTime> CRED_STAND_REV_DAT = new FinancialServicesReportingField<LocalDateTime>("BPCreditStandingReviewDate");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BusinessPartnerLoanToManager</b></p>
     * 
     * @return
     *     Loan to Manager According to Paragraph 15 German Banking Act
     */
    @SerializedName("BusinessPartnerLoanToManager")
    @JsonProperty("BusinessPartnerLoanToManager")
    @Nullable
    @ODataField(odataName = "BusinessPartnerLoanToManager")
    private String managLoanRecipient;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerLoanToManager</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> MANAG_LOAN_RECIPIENT = new FinancialServicesReportingField<String>("BusinessPartnerLoanToManager");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPCompanyRelationship</b></p>
     * 
     * @return
     *     Organization Relationship
     */
    @SerializedName("BPCompanyRelationship")
    @JsonProperty("BPCompanyRelationship")
    @Nullable
    @ODataField(odataName = "BPCompanyRelationship")
    private String orgRelation;
    /**
     * Use with available fluent helpers to apply the <b>BPCompanyRelationship</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> ORG_RELATION = new FinancialServicesReportingField<String>("BPCompanyRelationship");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>BPLoanReportingCreditorNumber</b></p>
     * 
     * @return
     *     Creditor Number for Reporting a Loan According to GBA
     */
    @SerializedName("BPLoanReportingCreditorNumber")
    @JsonProperty("BPLoanReportingCreditorNumber")
    @Nullable
    @ODataField(odataName = "BPLoanReportingCreditorNumber")
    private String creditorNumber;
    /**
     * Use with available fluent helpers to apply the <b>BPLoanReportingCreditorNumber</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> CREDITOR_NUMBER = new FinancialServicesReportingField<String>("BPLoanReportingCreditorNumber");
    /**
     * Constraints: Not nullable, Maximum length: 11 <p>Original property name from the Odata EDM: <b>BPOeNBIdentNumber</b></p>
     * 
     * @return
     *     (OeNB) Ident Number
     */
    @SerializedName("BPOeNBIdentNumber")
    @JsonProperty("BPOeNBIdentNumber")
    @Nullable
    @ODataField(odataName = "BPOeNBIdentNumber")
    private String oeNBIdentNumber;
    /**
     * Use with available fluent helpers to apply the <b>BPOeNBIdentNumber</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> OE_NB_IDENT_NUMBER = new FinancialServicesReportingField<String>("BPOeNBIdentNumber");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BPOeNBTargetGroup</b></p>
     * 
     * @return
     *     Target Group According to OeNB
     */
    @SerializedName("BPOeNBTargetGroup")
    @JsonProperty("BPOeNBTargetGroup")
    @Nullable
    @ODataField(odataName = "BPOeNBTargetGroup")
    private String oeNBTargetGrp;
    /**
     * Use with available fluent helpers to apply the <b>BPOeNBTargetGroup</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> OE_NB_TARGET_GRP = new FinancialServicesReportingField<String>("BPOeNBTargetGroup");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPOeNBIdentNumberAssigned</b></p>
     * 
     * @return
     *     Assign (OeNB) Ident Number
     */
    @SerializedName("BPOeNBIdentNumberAssigned")
    @JsonProperty("BPOeNBIdentNumberAssigned")
    @Nullable
    @ODataField(odataName = "BPOeNBIdentNumberAssigned")
    private String assignIdentNumber;
    /**
     * Use with available fluent helpers to apply the <b>BPOeNBIdentNumberAssigned</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> ASSIGN_IDENT_NUMBER = new FinancialServicesReportingField<String>("BPOeNBIdentNumberAssigned");
    /**
     * Constraints: Not nullable, Maximum length: 7 <p>Original property name from the Odata EDM: <b>BPOeNBInstituteNumber</b></p>
     * 
     * @return
     *     Institute Number According to OeNB
     */
    @SerializedName("BPOeNBInstituteNumber")
    @JsonProperty("BPOeNBInstituteNumber")
    @Nullable
    @ODataField(odataName = "BPOeNBInstituteNumber")
    private String oeNBInstNo;
    /**
     * Use with available fluent helpers to apply the <b>BPOeNBInstituteNumber</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> OE_NB_INST_NO = new FinancialServicesReportingField<String>("BPOeNBInstituteNumber");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BusinessPartnerIsOeNBInstitute</b></p>
     * 
     * @return
     *     Institute Subject to Austrian Reg. Reporting Requirements
     */
    @SerializedName("BusinessPartnerIsOeNBInstitute")
    @JsonProperty("BusinessPartnerIsOeNBInstitute")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BusinessPartnerIsOeNBInstitute")
    private Boolean oeNBRepInstit;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerIsOeNBInstitute</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<Boolean> OE_NB_REP_INSTIT = new FinancialServicesReportingField<Boolean>("BusinessPartnerIsOeNBInstitute");
    /**
     * Constraints: Not nullable, Maximum length: 15 <p>Original property name from the Odata EDM: <b>BusinessPartnerGroup</b></p>
     * 
     * @return
     *     Group ID
     */
    @SerializedName("BusinessPartnerGroup")
    @JsonProperty("BusinessPartnerGroup")
    @Nullable
    @ODataField(odataName = "BusinessPartnerGroup")
    private String groupID;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerGroup</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> GROUP_ID = new FinancialServicesReportingField<String>("BusinessPartnerGroup");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPGroupAssignmentCategory</b></p>
     * 
     * @return
     *     Group Assignment Category
     */
    @SerializedName("BPGroupAssignmentCategory")
    @JsonProperty("BPGroupAssignmentCategory")
    @Nullable
    @ODataField(odataName = "BPGroupAssignmentCategory")
    private String grpAssignmentCat;
    /**
     * Use with available fluent helpers to apply the <b>BPGroupAssignmentCategory</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> GRP_ASSIGNMENT_CAT = new FinancialServicesReportingField<String>("BPGroupAssignmentCategory");
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>BusinessPartnerGroupName</b></p>
     * 
     * @return
     *     Group Name
     */
    @SerializedName("BusinessPartnerGroupName")
    @JsonProperty("BusinessPartnerGroupName")
    @Nullable
    @ODataField(odataName = "BusinessPartnerGroupName")
    private String groupName;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerGroupName</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> GROUP_NAME = new FinancialServicesReportingField<String>("BusinessPartnerGroupName");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BusinessPartnerLegalEntity</b></p>
     * 
     * @return
     *     Legal Entity for Business Partner
     */
    @SerializedName("BusinessPartnerLegalEntity")
    @JsonProperty("BusinessPartnerLegalEntity")
    @Nullable
    @ODataField(odataName = "BusinessPartnerLegalEntity")
    private String legalEntity;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerLegalEntity</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> LEGAL_ENTITY = new FinancialServicesReportingField<String>("BusinessPartnerLegalEntity");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPGerAstRglnRestrictedAstQuota</b></p>
     * 
     * @return
     *     Business Partner Acc. to Para. 4, Sec. 2 of Asset Regulation
     */
    @SerializedName("BPGerAstRglnRestrictedAstQuota")
    @JsonProperty("BPGerAstRglnRestrictedAstQuota")
    @Nullable
    @ODataField(odataName = "BPGerAstRglnRestrictedAstQuota")
    private String par42AR;
    /**
     * Use with available fluent helpers to apply the <b>BPGerAstRglnRestrictedAstQuota</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> PAR42_A_R = new FinancialServicesReportingField<String>("BPGerAstRglnRestrictedAstQuota");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BusinessPartnerDebtorGroup</b></p>
     * 
     * @return
     *     Debtor Group According to German Law (BerVersV, Template 5)
     */
    @SerializedName("BusinessPartnerDebtorGroup")
    @JsonProperty("BusinessPartnerDebtorGroup")
    @Nullable
    @ODataField(odataName = "BusinessPartnerDebtorGroup")
    private String debtorGroup;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerDebtorGroup</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> DEBTOR_GROUP = new FinancialServicesReportingField<String>("BusinessPartnerDebtorGroup");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BusinessPartnerBusinessPurpose</b></p>
     * 
     * @return
     *     Category of Business Purpose
     */
    @SerializedName("BusinessPartnerBusinessPurpose")
    @JsonProperty("BusinessPartnerBusinessPurpose")
    @Nullable
    @ODataField(odataName = "BusinessPartnerBusinessPurpose")
    private String businessPurpose;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerBusinessPurpose</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> BUSINESS_PURPOSE = new FinancialServicesReportingField<String>("BusinessPartnerBusinessPurpose");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BusinessPartnerRiskGroup</b></p>
     * 
     * @return
     *     Risk Group
     */
    @SerializedName("BusinessPartnerRiskGroup")
    @JsonProperty("BusinessPartnerRiskGroup")
    @Nullable
    @ODataField(odataName = "BusinessPartnerRiskGroup")
    private String riskGroup;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerRiskGroup</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> RISK_GROUP = new FinancialServicesReportingField<String>("BusinessPartnerRiskGroup");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPRiskGroupingDate</b></p>
     * 
     * @return
     *     Date of Risk Grouping
     */
    @SerializedName("BPRiskGroupingDate")
    @JsonProperty("BPRiskGroupingDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPRiskGroupingDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime groupingDate;
    /**
     * Use with available fluent helpers to apply the <b>BPRiskGroupingDate</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<LocalDateTime> GROUPING_DATE = new FinancialServicesReportingField<LocalDateTime>("BPRiskGroupingDate");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPHasGroupAffiliation</b></p>
     * 
     * @return
     *     Group Affiliation Exists
     */
    @SerializedName("BPHasGroupAffiliation")
    @JsonProperty("BPHasGroupAffiliation")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BPHasGroupAffiliation")
    private Boolean groupAffiliation;
    /**
     * Use with available fluent helpers to apply the <b>BPHasGroupAffiliation</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<Boolean> GROUP_AFFILIATION = new FinancialServicesReportingField<Boolean>("BPHasGroupAffiliation");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPIsMonetaryFinInstitution</b></p>
     * 
     * @return
     *     Monetary Financial Institution
     */
    @SerializedName("BPIsMonetaryFinInstitution")
    @JsonProperty("BPIsMonetaryFinInstitution")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BPIsMonetaryFinInstitution")
    private Boolean monFinInstit;
    /**
     * Use with available fluent helpers to apply the <b>BPIsMonetaryFinInstitution</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<Boolean> MON_FIN_INSTIT = new FinancialServicesReportingField<Boolean>("BPIsMonetaryFinInstitution");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPCrdtStandingReviewIsRequired</b></p>
     * 
     * @return
     *     Obligation to Submit to Credit Standing Review - Para.18 GBA
     */
    @SerializedName("BPCrdtStandingReviewIsRequired")
    @JsonProperty("BPCrdtStandingReviewIsRequired")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BPCrdtStandingReviewIsRequired")
    private Boolean gBAPara18Relevant;
    /**
     * Use with available fluent helpers to apply the <b>BPCrdtStandingReviewIsRequired</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<Boolean> GBA_PARA18_RELEVANT = new FinancialServicesReportingField<Boolean>("BPCrdtStandingReviewIsRequired");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPLoanMonitoringIsRequired</b></p>
     * 
     * @return
     *     Large-Scale Loan Monitoring According to Paragraph 13b GBA
     */
    @SerializedName("BPLoanMonitoringIsRequired")
    @JsonProperty("BPLoanMonitoringIsRequired")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BPLoanMonitoringIsRequired")
    private Boolean lgeScaleLoanMon;
    /**
     * Use with available fluent helpers to apply the <b>BPLoanMonitoringIsRequired</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<Boolean> LGE_SCALE_LOAN_MON = new FinancialServicesReportingField<Boolean>("BPLoanMonitoringIsRequired");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPHasCreditingRelief</b></p>
     * 
     * @return
     *     Crediting Relief in Accordance with Paragraph 13/3 GBA
     */
    @SerializedName("BPHasCreditingRelief")
    @JsonProperty("BPHasCreditingRelief")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BPHasCreditingRelief")
    private Boolean creditingRelief;
    /**
     * Use with available fluent helpers to apply the <b>BPHasCreditingRelief</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<Boolean> CREDITING_RELIEF = new FinancialServicesReportingField<Boolean>("BPHasCreditingRelief");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPInvestInRstrcdAstIsAuthzd</b></p>
     * 
     * @return
     *     Authorized Acc. to Para. 2(1)18b of German Asset Regulation
     */
    @SerializedName("BPInvestInRstrcdAstIsAuthzd")
    @JsonProperty("BPInvestInRstrcdAstIsAuthzd")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BPInvestInRstrcdAstIsAuthzd")
    private Boolean para2118bGAR;
    /**
     * Use with available fluent helpers to apply the <b>BPInvestInRstrcdAstIsAuthzd</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<Boolean> PARA2118B_G_A_R = new FinancialServicesReportingField<Boolean>("BPInvestInRstrcdAstIsAuthzd");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>BPCentralBankCountryRegion</b></p>
     * 
     * @return
     *     Numeric Code for State Central Bank Country/Region Indicator
     */
    @SerializedName("BPCentralBankCountryRegion")
    @JsonProperty("BPCentralBankCountryRegion")
    @Nullable
    @ODataField(odataName = "BPCentralBankCountryRegion")
    private String sCBCntryRegInd;
    /**
     * Use with available fluent helpers to apply the <b>BPCentralBankCountryRegion</b> field to query operations.
     * 
     */
    public final static FinancialServicesReportingField<String> SCB_CNTRY_REG_IND = new FinancialServicesReportingField<String>("BPCentralBankCountryRegion");

    @Nonnull
    @Override
    public Class<FinancialServicesReporting> getType() {
        return FinancialServicesReporting.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>BusinessPartner</b></p>
     * 
     * @param businessPartner
     *     Business Partner Number
     */
    public void setBusinessPartner(
        @Nullable
        final String businessPartner) {
        rememberChangedField("BusinessPartner", this.businessPartner);
        this.businessPartner = businessPartner;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPIsNonResident</b></p>
     * 
     * @param nonResident
     *     Non-Resident According to Paragraph 4 AWG
     */
    public void setNonResident(
        @Nullable
        final Boolean nonResident) {
        rememberChangedField("BPIsNonResident", this.nonResident);
        this.nonResident = nonResident;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPNonResidencyStartDate</b></p>
     * 
     * @param nonResidentSince
     *     Start of Non-Residency According to Paragraph 4 AWG
     */
    public void setNonResidentSince(
        @Nullable
        final LocalDateTime nonResidentSince) {
        rememberChangedField("BPNonResidencyStartDate", this.nonResidentSince);
        this.nonResidentSince = nonResidentSince;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPIsMultimillionLoanRecipient</b></p>
     * 
     * @param multimillionLoan
     *     Recipient of Multimillion Loan According to Paragraph 14 GBA
     */
    public void setMultimillionLoan(
        @Nullable
        final Boolean multimillionLoan) {
        rememberChangedField("BPIsMultimillionLoanRecipient", this.multimillionLoan);
        this.multimillionLoan = multimillionLoan;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>BPLoanReportingBorrowerNumber</b></p>
     * 
     * @param borrowerNumber
     *     Borrower Number for Reporting a Loan According to GBA
     */
    public void setBorrowerNumber(
        @Nullable
        final String borrowerNumber) {
        rememberChangedField("BPLoanReportingBorrowerNumber", this.borrowerNumber);
        this.borrowerNumber = borrowerNumber;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>BPLoanRptgBorrowerEntityNumber</b></p>
     * 
     * @param borrEntityNo
     *     Borrower Entity Number Used to Report Loan acc. to GBA
     */
    public void setBorrEntityNo(
        @Nullable
        final String borrEntityNo) {
        rememberChangedField("BPLoanRptgBorrowerEntityNumber", this.borrEntityNo);
        this.borrEntityNo = borrEntityNo;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BPCreditStandingReview</b></p>
     * 
     * @param gBAInformation
     *     Credit Standing Review According to Paragraph 18 GBA
     */
    public void setGBAInformation(
        @Nullable
        final String gBAInformation) {
        rememberChangedField("BPCreditStandingReview", this.gBAInformation);
        this.gBAInformation = gBAInformation;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPCreditStandingReviewDate</b></p>
     * 
     * @param credStandRevDat
     *     Date of Credit Standing Review According to Paragraph 18 GBA
     */
    public void setCredStandRevDat(
        @Nullable
        final LocalDateTime credStandRevDat) {
        rememberChangedField("BPCreditStandingReviewDate", this.credStandRevDat);
        this.credStandRevDat = credStandRevDat;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BusinessPartnerLoanToManager</b></p>
     * 
     * @param managLoanRecipient
     *     Loan to Manager According to Paragraph 15 German Banking Act
     */
    public void setManagLoanRecipient(
        @Nullable
        final String managLoanRecipient) {
        rememberChangedField("BusinessPartnerLoanToManager", this.managLoanRecipient);
        this.managLoanRecipient = managLoanRecipient;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPCompanyRelationship</b></p>
     * 
     * @param orgRelation
     *     Organization Relationship
     */
    public void setOrgRelation(
        @Nullable
        final String orgRelation) {
        rememberChangedField("BPCompanyRelationship", this.orgRelation);
        this.orgRelation = orgRelation;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>BPLoanReportingCreditorNumber</b></p>
     * 
     * @param creditorNumber
     *     Creditor Number for Reporting a Loan According to GBA
     */
    public void setCreditorNumber(
        @Nullable
        final String creditorNumber) {
        rememberChangedField("BPLoanReportingCreditorNumber", this.creditorNumber);
        this.creditorNumber = creditorNumber;
    }

    /**
     * Constraints: Not nullable, Maximum length: 11 <p>Original property name from the Odata EDM: <b>BPOeNBIdentNumber</b></p>
     * 
     * @param oeNBIdentNumber
     *     (OeNB) Ident Number
     */
    public void setOeNBIdentNumber(
        @Nullable
        final String oeNBIdentNumber) {
        rememberChangedField("BPOeNBIdentNumber", this.oeNBIdentNumber);
        this.oeNBIdentNumber = oeNBIdentNumber;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BPOeNBTargetGroup</b></p>
     * 
     * @param oeNBTargetGrp
     *     Target Group According to OeNB
     */
    public void setOeNBTargetGrp(
        @Nullable
        final String oeNBTargetGrp) {
        rememberChangedField("BPOeNBTargetGroup", this.oeNBTargetGrp);
        this.oeNBTargetGrp = oeNBTargetGrp;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPOeNBIdentNumberAssigned</b></p>
     * 
     * @param assignIdentNumber
     *     Assign (OeNB) Ident Number
     */
    public void setAssignIdentNumber(
        @Nullable
        final String assignIdentNumber) {
        rememberChangedField("BPOeNBIdentNumberAssigned", this.assignIdentNumber);
        this.assignIdentNumber = assignIdentNumber;
    }

    /**
     * Constraints: Not nullable, Maximum length: 7 <p>Original property name from the Odata EDM: <b>BPOeNBInstituteNumber</b></p>
     * 
     * @param oeNBInstNo
     *     Institute Number According to OeNB
     */
    public void setOeNBInstNo(
        @Nullable
        final String oeNBInstNo) {
        rememberChangedField("BPOeNBInstituteNumber", this.oeNBInstNo);
        this.oeNBInstNo = oeNBInstNo;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BusinessPartnerIsOeNBInstitute</b></p>
     * 
     * @param oeNBRepInstit
     *     Institute Subject to Austrian Reg. Reporting Requirements
     */
    public void setOeNBRepInstit(
        @Nullable
        final Boolean oeNBRepInstit) {
        rememberChangedField("BusinessPartnerIsOeNBInstitute", this.oeNBRepInstit);
        this.oeNBRepInstit = oeNBRepInstit;
    }

    /**
     * Constraints: Not nullable, Maximum length: 15 <p>Original property name from the Odata EDM: <b>BusinessPartnerGroup</b></p>
     * 
     * @param groupID
     *     Group ID
     */
    public void setGroupID(
        @Nullable
        final String groupID) {
        rememberChangedField("BusinessPartnerGroup", this.groupID);
        this.groupID = groupID;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPGroupAssignmentCategory</b></p>
     * 
     * @param grpAssignmentCat
     *     Group Assignment Category
     */
    public void setGrpAssignmentCat(
        @Nullable
        final String grpAssignmentCat) {
        rememberChangedField("BPGroupAssignmentCategory", this.grpAssignmentCat);
        this.grpAssignmentCat = grpAssignmentCat;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>BusinessPartnerGroupName</b></p>
     * 
     * @param groupName
     *     Group Name
     */
    public void setGroupName(
        @Nullable
        final String groupName) {
        rememberChangedField("BusinessPartnerGroupName", this.groupName);
        this.groupName = groupName;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BusinessPartnerLegalEntity</b></p>
     * 
     * @param legalEntity
     *     Legal Entity for Business Partner
     */
    public void setLegalEntity(
        @Nullable
        final String legalEntity) {
        rememberChangedField("BusinessPartnerLegalEntity", this.legalEntity);
        this.legalEntity = legalEntity;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BPGerAstRglnRestrictedAstQuota</b></p>
     * 
     * @param par42AR
     *     Business Partner Acc. to Para. 4, Sec. 2 of Asset Regulation
     */
    public void setPar42AR(
        @Nullable
        final String par42AR) {
        rememberChangedField("BPGerAstRglnRestrictedAstQuota", this.par42AR);
        this.par42AR = par42AR;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BusinessPartnerDebtorGroup</b></p>
     * 
     * @param debtorGroup
     *     Debtor Group According to German Law (BerVersV, Template 5)
     */
    public void setDebtorGroup(
        @Nullable
        final String debtorGroup) {
        rememberChangedField("BusinessPartnerDebtorGroup", this.debtorGroup);
        this.debtorGroup = debtorGroup;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>BusinessPartnerBusinessPurpose</b></p>
     * 
     * @param businessPurpose
     *     Category of Business Purpose
     */
    public void setBusinessPurpose(
        @Nullable
        final String businessPurpose) {
        rememberChangedField("BusinessPartnerBusinessPurpose", this.businessPurpose);
        this.businessPurpose = businessPurpose;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BusinessPartnerRiskGroup</b></p>
     * 
     * @param riskGroup
     *     Risk Group
     */
    public void setRiskGroup(
        @Nullable
        final String riskGroup) {
        rememberChangedField("BusinessPartnerRiskGroup", this.riskGroup);
        this.riskGroup = riskGroup;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPRiskGroupingDate</b></p>
     * 
     * @param groupingDate
     *     Date of Risk Grouping
     */
    public void setGroupingDate(
        @Nullable
        final LocalDateTime groupingDate) {
        rememberChangedField("BPRiskGroupingDate", this.groupingDate);
        this.groupingDate = groupingDate;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPHasGroupAffiliation</b></p>
     * 
     * @param groupAffiliation
     *     Group Affiliation Exists
     */
    public void setGroupAffiliation(
        @Nullable
        final Boolean groupAffiliation) {
        rememberChangedField("BPHasGroupAffiliation", this.groupAffiliation);
        this.groupAffiliation = groupAffiliation;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPIsMonetaryFinInstitution</b></p>
     * 
     * @param monFinInstit
     *     Monetary Financial Institution
     */
    public void setMonFinInstit(
        @Nullable
        final Boolean monFinInstit) {
        rememberChangedField("BPIsMonetaryFinInstitution", this.monFinInstit);
        this.monFinInstit = monFinInstit;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPCrdtStandingReviewIsRequired</b></p>
     * 
     * @param gBAPara18Relevant
     *     Obligation to Submit to Credit Standing Review - Para.18 GBA
     */
    public void setGBAPara18Relevant(
        @Nullable
        final Boolean gBAPara18Relevant) {
        rememberChangedField("BPCrdtStandingReviewIsRequired", this.gBAPara18Relevant);
        this.gBAPara18Relevant = gBAPara18Relevant;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPLoanMonitoringIsRequired</b></p>
     * 
     * @param lgeScaleLoanMon
     *     Large-Scale Loan Monitoring According to Paragraph 13b GBA
     */
    public void setLgeScaleLoanMon(
        @Nullable
        final Boolean lgeScaleLoanMon) {
        rememberChangedField("BPLoanMonitoringIsRequired", this.lgeScaleLoanMon);
        this.lgeScaleLoanMon = lgeScaleLoanMon;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPHasCreditingRelief</b></p>
     * 
     * @param creditingRelief
     *     Crediting Relief in Accordance with Paragraph 13/3 GBA
     */
    public void setCreditingRelief(
        @Nullable
        final Boolean creditingRelief) {
        rememberChangedField("BPHasCreditingRelief", this.creditingRelief);
        this.creditingRelief = creditingRelief;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPInvestInRstrcdAstIsAuthzd</b></p>
     * 
     * @param para2118bGAR
     *     Authorized Acc. to Para. 2(1)18b of German Asset Regulation
     */
    public void setPara2118bGAR(
        @Nullable
        final Boolean para2118bGAR) {
        rememberChangedField("BPInvestInRstrcdAstIsAuthzd", this.para2118bGAR);
        this.para2118bGAR = para2118bGAR;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>BPCentralBankCountryRegion</b></p>
     * 
     * @param sCBCntryRegInd
     *     Numeric Code for State Central Bank Country/Region Indicator
     */
    public void setSCBCntryRegInd(
        @Nullable
        final String sCBCntryRegInd) {
        rememberChangedField("BPCentralBankCountryRegion", this.sCBCntryRegInd);
        this.sCBCntryRegInd = sCBCntryRegInd;
    }

    @Override
    protected String getEntityCollection() {
        return "A_BPFinancialServicesReporting";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("BusinessPartner", getBusinessPartner());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("BusinessPartner", getBusinessPartner());
        values.put("BPIsNonResident", getNonResident());
        values.put("BPNonResidencyStartDate", getNonResidentSince());
        values.put("BPIsMultimillionLoanRecipient", getMultimillionLoan());
        values.put("BPLoanReportingBorrowerNumber", getBorrowerNumber());
        values.put("BPLoanRptgBorrowerEntityNumber", getBorrEntityNo());
        values.put("BPCreditStandingReview", getGBAInformation());
        values.put("BPCreditStandingReviewDate", getCredStandRevDat());
        values.put("BusinessPartnerLoanToManager", getManagLoanRecipient());
        values.put("BPCompanyRelationship", getOrgRelation());
        values.put("BPLoanReportingCreditorNumber", getCreditorNumber());
        values.put("BPOeNBIdentNumber", getOeNBIdentNumber());
        values.put("BPOeNBTargetGroup", getOeNBTargetGrp());
        values.put("BPOeNBIdentNumberAssigned", getAssignIdentNumber());
        values.put("BPOeNBInstituteNumber", getOeNBInstNo());
        values.put("BusinessPartnerIsOeNBInstitute", getOeNBRepInstit());
        values.put("BusinessPartnerGroup", getGroupID());
        values.put("BPGroupAssignmentCategory", getGrpAssignmentCat());
        values.put("BusinessPartnerGroupName", getGroupName());
        values.put("BusinessPartnerLegalEntity", getLegalEntity());
        values.put("BPGerAstRglnRestrictedAstQuota", getPar42AR());
        values.put("BusinessPartnerDebtorGroup", getDebtorGroup());
        values.put("BusinessPartnerBusinessPurpose", getBusinessPurpose());
        values.put("BusinessPartnerRiskGroup", getRiskGroup());
        values.put("BPRiskGroupingDate", getGroupingDate());
        values.put("BPHasGroupAffiliation", getGroupAffiliation());
        values.put("BPIsMonetaryFinInstitution", getMonFinInstit());
        values.put("BPCrdtStandingReviewIsRequired", getGBAPara18Relevant());
        values.put("BPLoanMonitoringIsRequired", getLgeScaleLoanMon());
        values.put("BPHasCreditingRelief", getCreditingRelief());
        values.put("BPInvestInRstrcdAstIsAuthzd", getPara2118bGAR());
        values.put("BPCentralBankCountryRegion", getSCBCntryRegInd());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("BusinessPartner")) {
                final Object value = values.remove("BusinessPartner");
                if ((value == null)||(!value.equals(getBusinessPartner()))) {
                    setBusinessPartner(((String) value));
                }
            }
            if (values.containsKey("BPIsNonResident")) {
                final Object value = values.remove("BPIsNonResident");
                if ((value == null)||(!value.equals(getNonResident()))) {
                    setNonResident(((Boolean) value));
                }
            }
            if (values.containsKey("BPNonResidencyStartDate")) {
                final Object value = values.remove("BPNonResidencyStartDate");
                if ((value == null)||(!value.equals(getNonResidentSince()))) {
                    setNonResidentSince(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BPIsMultimillionLoanRecipient")) {
                final Object value = values.remove("BPIsMultimillionLoanRecipient");
                if ((value == null)||(!value.equals(getMultimillionLoan()))) {
                    setMultimillionLoan(((Boolean) value));
                }
            }
            if (values.containsKey("BPLoanReportingBorrowerNumber")) {
                final Object value = values.remove("BPLoanReportingBorrowerNumber");
                if ((value == null)||(!value.equals(getBorrowerNumber()))) {
                    setBorrowerNumber(((String) value));
                }
            }
            if (values.containsKey("BPLoanRptgBorrowerEntityNumber")) {
                final Object value = values.remove("BPLoanRptgBorrowerEntityNumber");
                if ((value == null)||(!value.equals(getBorrEntityNo()))) {
                    setBorrEntityNo(((String) value));
                }
            }
            if (values.containsKey("BPCreditStandingReview")) {
                final Object value = values.remove("BPCreditStandingReview");
                if ((value == null)||(!value.equals(getGBAInformation()))) {
                    setGBAInformation(((String) value));
                }
            }
            if (values.containsKey("BPCreditStandingReviewDate")) {
                final Object value = values.remove("BPCreditStandingReviewDate");
                if ((value == null)||(!value.equals(getCredStandRevDat()))) {
                    setCredStandRevDat(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BusinessPartnerLoanToManager")) {
                final Object value = values.remove("BusinessPartnerLoanToManager");
                if ((value == null)||(!value.equals(getManagLoanRecipient()))) {
                    setManagLoanRecipient(((String) value));
                }
            }
            if (values.containsKey("BPCompanyRelationship")) {
                final Object value = values.remove("BPCompanyRelationship");
                if ((value == null)||(!value.equals(getOrgRelation()))) {
                    setOrgRelation(((String) value));
                }
            }
            if (values.containsKey("BPLoanReportingCreditorNumber")) {
                final Object value = values.remove("BPLoanReportingCreditorNumber");
                if ((value == null)||(!value.equals(getCreditorNumber()))) {
                    setCreditorNumber(((String) value));
                }
            }
            if (values.containsKey("BPOeNBIdentNumber")) {
                final Object value = values.remove("BPOeNBIdentNumber");
                if ((value == null)||(!value.equals(getOeNBIdentNumber()))) {
                    setOeNBIdentNumber(((String) value));
                }
            }
            if (values.containsKey("BPOeNBTargetGroup")) {
                final Object value = values.remove("BPOeNBTargetGroup");
                if ((value == null)||(!value.equals(getOeNBTargetGrp()))) {
                    setOeNBTargetGrp(((String) value));
                }
            }
            if (values.containsKey("BPOeNBIdentNumberAssigned")) {
                final Object value = values.remove("BPOeNBIdentNumberAssigned");
                if ((value == null)||(!value.equals(getAssignIdentNumber()))) {
                    setAssignIdentNumber(((String) value));
                }
            }
            if (values.containsKey("BPOeNBInstituteNumber")) {
                final Object value = values.remove("BPOeNBInstituteNumber");
                if ((value == null)||(!value.equals(getOeNBInstNo()))) {
                    setOeNBInstNo(((String) value));
                }
            }
            if (values.containsKey("BusinessPartnerIsOeNBInstitute")) {
                final Object value = values.remove("BusinessPartnerIsOeNBInstitute");
                if ((value == null)||(!value.equals(getOeNBRepInstit()))) {
                    setOeNBRepInstit(((Boolean) value));
                }
            }
            if (values.containsKey("BusinessPartnerGroup")) {
                final Object value = values.remove("BusinessPartnerGroup");
                if ((value == null)||(!value.equals(getGroupID()))) {
                    setGroupID(((String) value));
                }
            }
            if (values.containsKey("BPGroupAssignmentCategory")) {
                final Object value = values.remove("BPGroupAssignmentCategory");
                if ((value == null)||(!value.equals(getGrpAssignmentCat()))) {
                    setGrpAssignmentCat(((String) value));
                }
            }
            if (values.containsKey("BusinessPartnerGroupName")) {
                final Object value = values.remove("BusinessPartnerGroupName");
                if ((value == null)||(!value.equals(getGroupName()))) {
                    setGroupName(((String) value));
                }
            }
            if (values.containsKey("BusinessPartnerLegalEntity")) {
                final Object value = values.remove("BusinessPartnerLegalEntity");
                if ((value == null)||(!value.equals(getLegalEntity()))) {
                    setLegalEntity(((String) value));
                }
            }
            if (values.containsKey("BPGerAstRglnRestrictedAstQuota")) {
                final Object value = values.remove("BPGerAstRglnRestrictedAstQuota");
                if ((value == null)||(!value.equals(getPar42AR()))) {
                    setPar42AR(((String) value));
                }
            }
            if (values.containsKey("BusinessPartnerDebtorGroup")) {
                final Object value = values.remove("BusinessPartnerDebtorGroup");
                if ((value == null)||(!value.equals(getDebtorGroup()))) {
                    setDebtorGroup(((String) value));
                }
            }
            if (values.containsKey("BusinessPartnerBusinessPurpose")) {
                final Object value = values.remove("BusinessPartnerBusinessPurpose");
                if ((value == null)||(!value.equals(getBusinessPurpose()))) {
                    setBusinessPurpose(((String) value));
                }
            }
            if (values.containsKey("BusinessPartnerRiskGroup")) {
                final Object value = values.remove("BusinessPartnerRiskGroup");
                if ((value == null)||(!value.equals(getRiskGroup()))) {
                    setRiskGroup(((String) value));
                }
            }
            if (values.containsKey("BPRiskGroupingDate")) {
                final Object value = values.remove("BPRiskGroupingDate");
                if ((value == null)||(!value.equals(getGroupingDate()))) {
                    setGroupingDate(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BPHasGroupAffiliation")) {
                final Object value = values.remove("BPHasGroupAffiliation");
                if ((value == null)||(!value.equals(getGroupAffiliation()))) {
                    setGroupAffiliation(((Boolean) value));
                }
            }
            if (values.containsKey("BPIsMonetaryFinInstitution")) {
                final Object value = values.remove("BPIsMonetaryFinInstitution");
                if ((value == null)||(!value.equals(getMonFinInstit()))) {
                    setMonFinInstit(((Boolean) value));
                }
            }
            if (values.containsKey("BPCrdtStandingReviewIsRequired")) {
                final Object value = values.remove("BPCrdtStandingReviewIsRequired");
                if ((value == null)||(!value.equals(getGBAPara18Relevant()))) {
                    setGBAPara18Relevant(((Boolean) value));
                }
            }
            if (values.containsKey("BPLoanMonitoringIsRequired")) {
                final Object value = values.remove("BPLoanMonitoringIsRequired");
                if ((value == null)||(!value.equals(getLgeScaleLoanMon()))) {
                    setLgeScaleLoanMon(((Boolean) value));
                }
            }
            if (values.containsKey("BPHasCreditingRelief")) {
                final Object value = values.remove("BPHasCreditingRelief");
                if ((value == null)||(!value.equals(getCreditingRelief()))) {
                    setCreditingRelief(((Boolean) value));
                }
            }
            if (values.containsKey("BPInvestInRstrcdAstIsAuthzd")) {
                final Object value = values.remove("BPInvestInRstrcdAstIsAuthzd");
                if ((value == null)||(!value.equals(getPara2118bGAR()))) {
                    setPara2118bGAR(((Boolean) value));
                }
            }
            if (values.containsKey("BPCentralBankCountryRegion")) {
                final Object value = values.remove("BPCentralBankCountryRegion");
                if ((value == null)||(!value.equals(getSCBCntryRegInd()))) {
                    setSCBCntryRegInd(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >FinancialServicesReportingField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new FinancialServicesReportingField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >FinancialServicesReportingField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new FinancialServicesReportingField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public Destination getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final Destination destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return (com.sap.cloud.sdk.tutorial.datamodel.odata.services.BusinessPartnerService.DEFAULT_SERVICE_PATH);
    }

}
