
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.1.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.FiscalYearInformationField;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable.FiscalYearInformationSelectable;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * Fiscal Year Information<p></p><p>Original entity name from the Odata EDM: <b>A_BPFiscalYearInformationType</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class FiscalYearInformation
    extends VdmEntity<FiscalYearInformation>
{

    /**
     * Selector for all available fields of FiscalYearInformation.
     * 
     */
    public final static FiscalYearInformationSelectable ALL_FIELDS = () -> "*";
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>BusinessPartner</b></p>
     * 
     * @return
     *     Business Partner Number
     */
    @Key
    @SerializedName("BusinessPartner")
    @JsonProperty("BusinessPartner")
    @Nullable
    @ODataField(odataName = "BusinessPartner")
    private String businessPartner;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartner</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<String> BUSINESS_PARTNER = new FiscalYearInformationField<String>("BusinessPartner");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>BusinessPartnerFiscalYear</b></p>
     * 
     * @return
     *     Fiscal year
     */
    @Key
    @SerializedName("BusinessPartnerFiscalYear")
    @JsonProperty("BusinessPartnerFiscalYear")
    @Nullable
    @ODataField(odataName = "BusinessPartnerFiscalYear")
    private String fiscalYear;
    /**
     * Use with available fluent helpers to apply the <b>BusinessPartnerFiscalYear</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<String> FISCAL_YEAR = new FiscalYearInformationField<String>("BusinessPartnerFiscalYear");
    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>BPBalanceSheetCurrency</b></p>
     * 
     * @return
     *     Balance Sheet Currency
     */
    @SerializedName("BPBalanceSheetCurrency")
    @JsonProperty("BPBalanceSheetCurrency")
    @Nullable
    @ODataField(odataName = "BPBalanceSheetCurrency")
    private String balSheetCurrency;
    /**
     * Use with available fluent helpers to apply the <b>BPBalanceSheetCurrency</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<String> BAL_SHEET_CURRENCY = new FiscalYearInformationField<String>("BPBalanceSheetCurrency");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPAnnualStockholderMeetingDate</b></p>
     * 
     * @return
     *     Date of Annual Stockholders Meeting
     */
    @SerializedName("BPAnnualStockholderMeetingDate")
    @JsonProperty("BPAnnualStockholderMeetingDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPAnnualStockholderMeetingDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime annStckholdMeeting;
    /**
     * Use with available fluent helpers to apply the <b>BPAnnualStockholderMeetingDate</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<LocalDateTime> ANN_STCKHOLD_MEETING = new FiscalYearInformationField<LocalDateTime>("BPAnnualStockholderMeetingDate");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPFiscalYearStartDate</b></p>
     * 
     * @return
     *     Fiscal Year Start Date
     */
    @SerializedName("BPFiscalYearStartDate")
    @JsonProperty("BPFiscalYearStartDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPFiscalYearStartDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime fiscYearStartDate;
    /**
     * Use with available fluent helpers to apply the <b>BPFiscalYearStartDate</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<LocalDateTime> FISC_YEAR_START_DATE = new FiscalYearInformationField<LocalDateTime>("BPFiscalYearStartDate");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPFiscalYearEndDate</b></p>
     * 
     * @return
     *     Fiscal Year End Date
     */
    @SerializedName("BPFiscalYearEndDate")
    @JsonProperty("BPFiscalYearEndDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPFiscalYearEndDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime fiscalYearEnd;
    /**
     * Use with available fluent helpers to apply the <b>BPFiscalYearEndDate</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<LocalDateTime> FISCAL_YEAR_END = new FiscalYearInformationField<LocalDateTime>("BPFiscalYearEndDate");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPFiscalYearIsClosed</b></p>
     * 
     * @return
     *     Year-End Closing
     */
    @SerializedName("BPFiscalYearIsClosed")
    @JsonProperty("BPFiscalYearIsClosed")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "BPFiscalYearIsClosed")
    private Boolean yearEndClosing;
    /**
     * Use with available fluent helpers to apply the <b>BPFiscalYearIsClosed</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<Boolean> YEAR_END_CLOSING = new FiscalYearInformationField<Boolean>("BPFiscalYearIsClosed");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPFiscalYearClosingDate</b></p>
     * 
     * @return
     *     Year-End Closing Date for Fiscal Year
     */
    @SerializedName("BPFiscalYearClosingDate")
    @JsonProperty("BPFiscalYearClosingDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPFiscalYearClosingDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime yearEndClosing_2;
    /**
     * Use with available fluent helpers to apply the <b>BPFiscalYearClosingDate</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<LocalDateTime> YEAR_END_CLOSING_2 = new FiscalYearInformationField<LocalDateTime>("BPFiscalYearClosingDate");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPFsclYrCnsldtdFinStatementDte</b></p>
     * 
     * @return
     *     Date of Consolidated Financial Statements of Group Company
     */
    @SerializedName("BPFsclYrCnsldtdFinStatementDte")
    @JsonProperty("BPFsclYrCnsldtdFinStatementDte")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "BPFsclYrCnsldtdFinStatementDte", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime consFinStatements;
    /**
     * Use with available fluent helpers to apply the <b>BPFsclYrCnsldtdFinStatementDte</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<LocalDateTime> CONS_FIN_STATEMENTS = new FiscalYearInformationField<LocalDateTime>("BPFsclYrCnsldtdFinStatementDte");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPCapitalStockAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Authorized Capital Stock for Company
     */
    @SerializedName("BPCapitalStockAmtInBalShtCrcy")
    @JsonProperty("BPCapitalStockAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPCapitalStockAmtInBalShtCrcy")
    private BigDecimal capitalStock;
    /**
     * Use with available fluent helpers to apply the <b>BPCapitalStockAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> CAPITAL_STOCK = new FiscalYearInformationField<BigDecimal>("BPCapitalStockAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPIssdStockCptlAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Issued Stock Capital for Company
     */
    @SerializedName("BPIssdStockCptlAmtInBalShtCrcy")
    @JsonProperty("BPIssdStockCptlAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPIssdStockCptlAmtInBalShtCrcy")
    private BigDecimal issuedStockCapital;
    /**
     * Use with available fluent helpers to apply the <b>BPIssdStockCptlAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> ISSUED_STOCK_CAPITAL = new FiscalYearInformationField<BigDecimal>("BPIssdStockCptlAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPPartcipnCertAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Participation Certificates Outstanding for Company
     */
    @SerializedName("BPPartcipnCertAmtInBalShtCrcy")
    @JsonProperty("BPPartcipnCertAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPPartcipnCertAmtInBalShtCrcy")
    private BigDecimal partCertsOutstand;
    /**
     * Use with available fluent helpers to apply the <b>BPPartcipnCertAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> PART_CERTS_OUTSTAND = new FiscalYearInformationField<BigDecimal>("BPPartcipnCertAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPEquityCapitalAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Equity Capital for Company
     */
    @SerializedName("BPEquityCapitalAmtInBalShtCrcy")
    @JsonProperty("BPEquityCapitalAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPEquityCapitalAmtInBalShtCrcy")
    private BigDecimal equityCapital;
    /**
     * Use with available fluent helpers to apply the <b>BPEquityCapitalAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> EQUITY_CAPITAL = new FiscalYearInformationField<BigDecimal>("BPEquityCapitalAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPGrossPremiumAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Gross Premium
     */
    @SerializedName("BPGrossPremiumAmtInBalShtCrcy")
    @JsonProperty("BPGrossPremiumAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPGrossPremiumAmtInBalShtCrcy")
    private BigDecimal grossPremium;
    /**
     * Use with available fluent helpers to apply the <b>BPGrossPremiumAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> GROSS_PREMIUM = new FiscalYearInformationField<BigDecimal>("BPGrossPremiumAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPNetPremiumAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Net Premium
     */
    @SerializedName("BPNetPremiumAmtInBalShtCrcy")
    @JsonProperty("BPNetPremiumAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPNetPremiumAmtInBalShtCrcy")
    private BigDecimal netPremium;
    /**
     * Use with available fluent helpers to apply the <b>BPNetPremiumAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> NET_PREMIUM = new FiscalYearInformationField<BigDecimal>("BPNetPremiumAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPAnnualSalesAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Annual Sales for Company
     */
    @SerializedName("BPAnnualSalesAmtInBalShtCrcy")
    @JsonProperty("BPAnnualSalesAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPAnnualSalesAmtInBalShtCrcy")
    private BigDecimal annualSales;
    /**
     * Use with available fluent helpers to apply the <b>BPAnnualSalesAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> ANNUAL_SALES = new FiscalYearInformationField<BigDecimal>("BPAnnualSalesAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPAnnualNetIncAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Annual Net Income/Net Loss for Company
     */
    @SerializedName("BPAnnualNetIncAmtInBalShtCrcy")
    @JsonProperty("BPAnnualNetIncAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPAnnualNetIncAmtInBalShtCrcy")
    private BigDecimal annualNetIncome;
    /**
     * Use with available fluent helpers to apply the <b>BPAnnualNetIncAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> ANNUAL_NET_INCOME = new FiscalYearInformationField<BigDecimal>("BPAnnualNetIncAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPDividendDistrAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Dividend/Profit Distribution Amount for Company
     */
    @SerializedName("BPDividendDistrAmtInBalShtCrcy")
    @JsonProperty("BPDividendDistrAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPDividendDistrAmtInBalShtCrcy")
    private BigDecimal dividend;
    /**
     * Use with available fluent helpers to apply the <b>BPDividendDistrAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> DIVIDEND = new FiscalYearInformationField<BigDecimal>("BPDividendDistrAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 6, Scale: 3 <p>Original property name from the Odata EDM: <b>BPDebtRatioInYears</b></p>
     * 
     * @return
     *     Debt Ratio in Years
     */
    @SerializedName("BPDebtRatioInYears")
    @JsonProperty("BPDebtRatioInYears")
    @Nullable
    @ODataField(odataName = "BPDebtRatioInYears")
    private BigDecimal debtRatio;
    /**
     * Use with available fluent helpers to apply the <b>BPDebtRatioInYears</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> DEBT_RATIO = new FiscalYearInformationField<BigDecimal>("BPDebtRatioInYears");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPAnnualPnLAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Annual Profit/Loss for Organization
     */
    @SerializedName("BPAnnualPnLAmtInBalShtCrcy")
    @JsonProperty("BPAnnualPnLAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPAnnualPnLAmtInBalShtCrcy")
    private BigDecimal reportedProfit;
    /**
     * Use with available fluent helpers to apply the <b>BPAnnualPnLAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> REPORTED_PROFIT = new FiscalYearInformationField<BigDecimal>("BPAnnualPnLAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPBalSheetTotalAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Balance Sheet Total for Company
     */
    @SerializedName("BPBalSheetTotalAmtInBalShtCrcy")
    @JsonProperty("BPBalSheetTotalAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPBalSheetTotalAmtInBalShtCrcy")
    private BigDecimal balanceSheetTotal;
    /**
     * Use with available fluent helpers to apply the <b>BPBalSheetTotalAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> BALANCE_SHEET_TOTAL = new FiscalYearInformationField<BigDecimal>("BPBalSheetTotalAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Maximum length: 7 <p>Original property name from the Odata EDM: <b>BPNumberOfEmployees</b></p>
     * 
     * @return
     *     Number of Employees in Company
     */
    @SerializedName("BPNumberOfEmployees")
    @JsonProperty("BPNumberOfEmployees")
    @Nullable
    @ODataField(odataName = "BPNumberOfEmployees")
    private String numberOfEmployees;
    /**
     * Use with available fluent helpers to apply the <b>BPNumberOfEmployees</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<String> NUMBER_OF_EMPLOYEES = new FiscalYearInformationField<String>("BPNumberOfEmployees");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPCptlReserveAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Capital Reserve for Company
     */
    @SerializedName("BPCptlReserveAmtInBalShtCrcy")
    @JsonProperty("BPCptlReserveAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPCptlReserveAmtInBalShtCrcy")
    private BigDecimal capitalReserve;
    /**
     * Use with available fluent helpers to apply the <b>BPCptlReserveAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> CAPITAL_RESERVE = new FiscalYearInformationField<BigDecimal>("BPCptlReserveAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPLglRevnRsrvAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Legal Revenue Reserves for Company
     */
    @SerializedName("BPLglRevnRsrvAmtInBalShtCrcy")
    @JsonProperty("BPLglRevnRsrvAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPLglRevnRsrvAmtInBalShtCrcy")
    private BigDecimal legalRevenueRes;
    /**
     * Use with available fluent helpers to apply the <b>BPLglRevnRsrvAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> LEGAL_REVENUE_RES = new FiscalYearInformationField<BigDecimal>("BPLglRevnRsrvAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>RevnRsrvOwnStkAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Revenue Reserves for Own Stock
     */
    @SerializedName("RevnRsrvOwnStkAmtInBalShtCrcy")
    @JsonProperty("RevnRsrvOwnStkAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "RevnRsrvOwnStkAmtInBalShtCrcy")
    private BigDecimal revReservesOwnSt;
    /**
     * Use with available fluent helpers to apply the <b>RevnRsrvOwnStkAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> REV_RESERVES_OWN_ST = new FiscalYearInformationField<BigDecimal>("RevnRsrvOwnStkAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPStatryReserveAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Statutory Revenue Reserve for Company
     */
    @SerializedName("BPStatryReserveAmtInBalShtCrcy")
    @JsonProperty("BPStatryReserveAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPStatryReserveAmtInBalShtCrcy")
    private BigDecimal statutoryReserve;
    /**
     * Use with available fluent helpers to apply the <b>BPStatryReserveAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> STATUTORY_RESERVE = new FiscalYearInformationField<BigDecimal>("BPStatryReserveAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPOthRevnRsrvAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Other Revenue Reserves for Company
     */
    @SerializedName("BPOthRevnRsrvAmtInBalShtCrcy")
    @JsonProperty("BPOthRevnRsrvAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPOthRevnRsrvAmtInBalShtCrcy")
    private BigDecimal otherRevenueRes;
    /**
     * Use with available fluent helpers to apply the <b>BPOthRevnRsrvAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> OTHER_REVENUE_RES = new FiscalYearInformationField<BigDecimal>("BPOthRevnRsrvAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPPnLCarryfwdAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Profit/Loss Carried Forward for Company
     */
    @SerializedName("BPPnLCarryfwdAmtInBalShtCrcy")
    @JsonProperty("BPPnLCarryfwdAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPPnLCarryfwdAmtInBalShtCrcy")
    private BigDecimal pLCarriedFwd;
    /**
     * Use with available fluent helpers to apply the <b>BPPnLCarryfwdAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> PL_CARRIED_FWD = new FiscalYearInformationField<BigDecimal>("BPPnLCarryfwdAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPSuborddLbltyAmtInBalShtCrcy</b></p>
     * 
     * @return
     *     Amount of Subordinated Liabilities for Company
     */
    @SerializedName("BPSuborddLbltyAmtInBalShtCrcy")
    @JsonProperty("BPSuborddLbltyAmtInBalShtCrcy")
    @Nullable
    @ODataField(odataName = "BPSuborddLbltyAmtInBalShtCrcy")
    private BigDecimal subordLiabilities;
    /**
     * Use with available fluent helpers to apply the <b>BPSuborddLbltyAmtInBalShtCrcy</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> SUBORD_LIABILITIES = new FiscalYearInformationField<BigDecimal>("BPSuborddLbltyAmtInBalShtCrcy");
    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>BPRetOnTotalCptlEmpldInPercent</b></p>
     * 
     * @return
     *     Return on Total Capital Employed for Company in Percent
     */
    @SerializedName("BPRetOnTotalCptlEmpldInPercent")
    @JsonProperty("BPRetOnTotalCptlEmpldInPercent")
    @Nullable
    @ODataField(odataName = "BPRetOnTotalCptlEmpldInPercent")
    private BigDecimal returnOnTotCap;
    /**
     * Use with available fluent helpers to apply the <b>BPRetOnTotalCptlEmpldInPercent</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> RETURN_ON_TOT_CAP = new FiscalYearInformationField<BigDecimal>("BPRetOnTotalCptlEmpldInPercent");
    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>BPDebtClearancePeriodInYears</b></p>
     * 
     * @return
     *     Debt Clearance Period in Years
     */
    @SerializedName("BPDebtClearancePeriodInYears")
    @JsonProperty("BPDebtClearancePeriodInYears")
    @Nullable
    @ODataField(odataName = "BPDebtClearancePeriodInYears")
    private BigDecimal debtClearancePer;
    /**
     * Use with available fluent helpers to apply the <b>BPDebtClearancePeriodInYears</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> DEBT_CLEARANCE_PER = new FiscalYearInformationField<BigDecimal>("BPDebtClearancePeriodInYears");
    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>BPFinancingCoeffInPercent</b></p>
     * 
     * @return
     *     Financing Coefficient for Company in Percent
     */
    @SerializedName("BPFinancingCoeffInPercent")
    @JsonProperty("BPFinancingCoeffInPercent")
    @Nullable
    @ODataField(odataName = "BPFinancingCoeffInPercent")
    private BigDecimal financingCoeff;
    /**
     * Use with available fluent helpers to apply the <b>BPFinancingCoeffInPercent</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> FINANCING_COEFF = new FiscalYearInformationField<BigDecimal>("BPFinancingCoeffInPercent");
    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>BPEquityRatioInPercent</b></p>
     * 
     * @return
     *     Equity Ratio of Company in Percent
     */
    @SerializedName("BPEquityRatioInPercent")
    @JsonProperty("BPEquityRatioInPercent")
    @Nullable
    @ODataField(odataName = "BPEquityRatioInPercent")
    private BigDecimal equityRatio;
    /**
     * Use with available fluent helpers to apply the <b>BPEquityRatioInPercent</b> field to query operations.
     * 
     */
    public final static FiscalYearInformationField<BigDecimal> EQUITY_RATIO = new FiscalYearInformationField<BigDecimal>("BPEquityRatioInPercent");

    @Nonnull
    @Override
    public Class<FiscalYearInformation> getType() {
        return FiscalYearInformation.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>BusinessPartner</b></p>
     * 
     * @param businessPartner
     *     Business Partner Number
     */
    public void setBusinessPartner(
        @Nullable
        final String businessPartner) {
        rememberChangedField("BusinessPartner", this.businessPartner);
        this.businessPartner = businessPartner;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>BusinessPartnerFiscalYear</b></p>
     * 
     * @param fiscalYear
     *     Fiscal year
     */
    public void setFiscalYear(
        @Nullable
        final String fiscalYear) {
        rememberChangedField("BusinessPartnerFiscalYear", this.fiscalYear);
        this.fiscalYear = fiscalYear;
    }

    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>BPBalanceSheetCurrency</b></p>
     * 
     * @param balSheetCurrency
     *     Balance Sheet Currency
     */
    public void setBalSheetCurrency(
        @Nullable
        final String balSheetCurrency) {
        rememberChangedField("BPBalanceSheetCurrency", this.balSheetCurrency);
        this.balSheetCurrency = balSheetCurrency;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPAnnualStockholderMeetingDate</b></p>
     * 
     * @param annStckholdMeeting
     *     Date of Annual Stockholders Meeting
     */
    public void setAnnStckholdMeeting(
        @Nullable
        final LocalDateTime annStckholdMeeting) {
        rememberChangedField("BPAnnualStockholderMeetingDate", this.annStckholdMeeting);
        this.annStckholdMeeting = annStckholdMeeting;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPFiscalYearStartDate</b></p>
     * 
     * @param fiscYearStartDate
     *     Fiscal Year Start Date
     */
    public void setFiscYearStartDate(
        @Nullable
        final LocalDateTime fiscYearStartDate) {
        rememberChangedField("BPFiscalYearStartDate", this.fiscYearStartDate);
        this.fiscYearStartDate = fiscYearStartDate;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPFiscalYearEndDate</b></p>
     * 
     * @param fiscalYearEnd
     *     Fiscal Year End Date
     */
    public void setFiscalYearEnd(
        @Nullable
        final LocalDateTime fiscalYearEnd) {
        rememberChangedField("BPFiscalYearEndDate", this.fiscalYearEnd);
        this.fiscalYearEnd = fiscalYearEnd;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>BPFiscalYearIsClosed</b></p>
     * 
     * @param yearEndClosing
     *     Year-End Closing
     */
    public void setYearEndClosing(
        @Nullable
        final Boolean yearEndClosing) {
        rememberChangedField("BPFiscalYearIsClosed", this.yearEndClosing);
        this.yearEndClosing = yearEndClosing;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPFiscalYearClosingDate</b></p>
     * 
     * @param yearEndClosing_2
     *     Year-End Closing Date for Fiscal Year
     */
    public void setYearEndClosing_2(
        @Nullable
        final LocalDateTime yearEndClosing_2) {
        rememberChangedField("BPFiscalYearClosingDate", this.yearEndClosing_2);
        this.yearEndClosing_2 = yearEndClosing_2;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>BPFsclYrCnsldtdFinStatementDte</b></p>
     * 
     * @param consFinStatements
     *     Date of Consolidated Financial Statements of Group Company
     */
    public void setConsFinStatements(
        @Nullable
        final LocalDateTime consFinStatements) {
        rememberChangedField("BPFsclYrCnsldtdFinStatementDte", this.consFinStatements);
        this.consFinStatements = consFinStatements;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPCapitalStockAmtInBalShtCrcy</b></p>
     * 
     * @param capitalStock
     *     Amount of Authorized Capital Stock for Company
     */
    public void setCapitalStock(
        @Nullable
        final BigDecimal capitalStock) {
        rememberChangedField("BPCapitalStockAmtInBalShtCrcy", this.capitalStock);
        this.capitalStock = capitalStock;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPIssdStockCptlAmtInBalShtCrcy</b></p>
     * 
     * @param issuedStockCapital
     *     Amount of Issued Stock Capital for Company
     */
    public void setIssuedStockCapital(
        @Nullable
        final BigDecimal issuedStockCapital) {
        rememberChangedField("BPIssdStockCptlAmtInBalShtCrcy", this.issuedStockCapital);
        this.issuedStockCapital = issuedStockCapital;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPPartcipnCertAmtInBalShtCrcy</b></p>
     * 
     * @param partCertsOutstand
     *     Amount of Participation Certificates Outstanding for Company
     */
    public void setPartCertsOutstand(
        @Nullable
        final BigDecimal partCertsOutstand) {
        rememberChangedField("BPPartcipnCertAmtInBalShtCrcy", this.partCertsOutstand);
        this.partCertsOutstand = partCertsOutstand;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPEquityCapitalAmtInBalShtCrcy</b></p>
     * 
     * @param equityCapital
     *     Amount of Equity Capital for Company
     */
    public void setEquityCapital(
        @Nullable
        final BigDecimal equityCapital) {
        rememberChangedField("BPEquityCapitalAmtInBalShtCrcy", this.equityCapital);
        this.equityCapital = equityCapital;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPGrossPremiumAmtInBalShtCrcy</b></p>
     * 
     * @param grossPremium
     *     Gross Premium
     */
    public void setGrossPremium(
        @Nullable
        final BigDecimal grossPremium) {
        rememberChangedField("BPGrossPremiumAmtInBalShtCrcy", this.grossPremium);
        this.grossPremium = grossPremium;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPNetPremiumAmtInBalShtCrcy</b></p>
     * 
     * @param netPremium
     *     Net Premium
     */
    public void setNetPremium(
        @Nullable
        final BigDecimal netPremium) {
        rememberChangedField("BPNetPremiumAmtInBalShtCrcy", this.netPremium);
        this.netPremium = netPremium;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPAnnualSalesAmtInBalShtCrcy</b></p>
     * 
     * @param annualSales
     *     Amount of Annual Sales for Company
     */
    public void setAnnualSales(
        @Nullable
        final BigDecimal annualSales) {
        rememberChangedField("BPAnnualSalesAmtInBalShtCrcy", this.annualSales);
        this.annualSales = annualSales;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPAnnualNetIncAmtInBalShtCrcy</b></p>
     * 
     * @param annualNetIncome
     *     Amount of Annual Net Income/Net Loss for Company
     */
    public void setAnnualNetIncome(
        @Nullable
        final BigDecimal annualNetIncome) {
        rememberChangedField("BPAnnualNetIncAmtInBalShtCrcy", this.annualNetIncome);
        this.annualNetIncome = annualNetIncome;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPDividendDistrAmtInBalShtCrcy</b></p>
     * 
     * @param dividend
     *     Dividend/Profit Distribution Amount for Company
     */
    public void setDividend(
        @Nullable
        final BigDecimal dividend) {
        rememberChangedField("BPDividendDistrAmtInBalShtCrcy", this.dividend);
        this.dividend = dividend;
    }

    /**
     * Constraints: Not nullable, Precision: 6, Scale: 3 <p>Original property name from the Odata EDM: <b>BPDebtRatioInYears</b></p>
     * 
     * @param debtRatio
     *     Debt Ratio in Years
     */
    public void setDebtRatio(
        @Nullable
        final BigDecimal debtRatio) {
        rememberChangedField("BPDebtRatioInYears", this.debtRatio);
        this.debtRatio = debtRatio;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPAnnualPnLAmtInBalShtCrcy</b></p>
     * 
     * @param reportedProfit
     *     Amount of Annual Profit/Loss for Organization
     */
    public void setReportedProfit(
        @Nullable
        final BigDecimal reportedProfit) {
        rememberChangedField("BPAnnualPnLAmtInBalShtCrcy", this.reportedProfit);
        this.reportedProfit = reportedProfit;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPBalSheetTotalAmtInBalShtCrcy</b></p>
     * 
     * @param balanceSheetTotal
     *     Amount of Balance Sheet Total for Company
     */
    public void setBalanceSheetTotal(
        @Nullable
        final BigDecimal balanceSheetTotal) {
        rememberChangedField("BPBalSheetTotalAmtInBalShtCrcy", this.balanceSheetTotal);
        this.balanceSheetTotal = balanceSheetTotal;
    }

    /**
     * Constraints: Not nullable, Maximum length: 7 <p>Original property name from the Odata EDM: <b>BPNumberOfEmployees</b></p>
     * 
     * @param numberOfEmployees
     *     Number of Employees in Company
     */
    public void setNumberOfEmployees(
        @Nullable
        final String numberOfEmployees) {
        rememberChangedField("BPNumberOfEmployees", this.numberOfEmployees);
        this.numberOfEmployees = numberOfEmployees;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPCptlReserveAmtInBalShtCrcy</b></p>
     * 
     * @param capitalReserve
     *     Amount of Capital Reserve for Company
     */
    public void setCapitalReserve(
        @Nullable
        final BigDecimal capitalReserve) {
        rememberChangedField("BPCptlReserveAmtInBalShtCrcy", this.capitalReserve);
        this.capitalReserve = capitalReserve;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPLglRevnRsrvAmtInBalShtCrcy</b></p>
     * 
     * @param legalRevenueRes
     *     Amount of Legal Revenue Reserves for Company
     */
    public void setLegalRevenueRes(
        @Nullable
        final BigDecimal legalRevenueRes) {
        rememberChangedField("BPLglRevnRsrvAmtInBalShtCrcy", this.legalRevenueRes);
        this.legalRevenueRes = legalRevenueRes;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>RevnRsrvOwnStkAmtInBalShtCrcy</b></p>
     * 
     * @param revReservesOwnSt
     *     Revenue Reserves for Own Stock
     */
    public void setRevReservesOwnSt(
        @Nullable
        final BigDecimal revReservesOwnSt) {
        rememberChangedField("RevnRsrvOwnStkAmtInBalShtCrcy", this.revReservesOwnSt);
        this.revReservesOwnSt = revReservesOwnSt;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPStatryReserveAmtInBalShtCrcy</b></p>
     * 
     * @param statutoryReserve
     *     Amount of Statutory Revenue Reserve for Company
     */
    public void setStatutoryReserve(
        @Nullable
        final BigDecimal statutoryReserve) {
        rememberChangedField("BPStatryReserveAmtInBalShtCrcy", this.statutoryReserve);
        this.statutoryReserve = statutoryReserve;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPOthRevnRsrvAmtInBalShtCrcy</b></p>
     * 
     * @param otherRevenueRes
     *     Amount of Other Revenue Reserves for Company
     */
    public void setOtherRevenueRes(
        @Nullable
        final BigDecimal otherRevenueRes) {
        rememberChangedField("BPOthRevnRsrvAmtInBalShtCrcy", this.otherRevenueRes);
        this.otherRevenueRes = otherRevenueRes;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPPnLCarryfwdAmtInBalShtCrcy</b></p>
     * 
     * @param pLCarriedFwd
     *     Amount of Profit/Loss Carried Forward for Company
     */
    public void setPLCarriedFwd(
        @Nullable
        final BigDecimal pLCarriedFwd) {
        rememberChangedField("BPPnLCarryfwdAmtInBalShtCrcy", this.pLCarriedFwd);
        this.pLCarriedFwd = pLCarriedFwd;
    }

    /**
     * Constraints: Not nullable, Precision: 16, Scale: 3 <p>Original property name from the Odata EDM: <b>BPSuborddLbltyAmtInBalShtCrcy</b></p>
     * 
     * @param subordLiabilities
     *     Amount of Subordinated Liabilities for Company
     */
    public void setSubordLiabilities(
        @Nullable
        final BigDecimal subordLiabilities) {
        rememberChangedField("BPSuborddLbltyAmtInBalShtCrcy", this.subordLiabilities);
        this.subordLiabilities = subordLiabilities;
    }

    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>BPRetOnTotalCptlEmpldInPercent</b></p>
     * 
     * @param returnOnTotCap
     *     Return on Total Capital Employed for Company in Percent
     */
    public void setReturnOnTotCap(
        @Nullable
        final BigDecimal returnOnTotCap) {
        rememberChangedField("BPRetOnTotalCptlEmpldInPercent", this.returnOnTotCap);
        this.returnOnTotCap = returnOnTotCap;
    }

    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>BPDebtClearancePeriodInYears</b></p>
     * 
     * @param debtClearancePer
     *     Debt Clearance Period in Years
     */
    public void setDebtClearancePer(
        @Nullable
        final BigDecimal debtClearancePer) {
        rememberChangedField("BPDebtClearancePeriodInYears", this.debtClearancePer);
        this.debtClearancePer = debtClearancePer;
    }

    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>BPFinancingCoeffInPercent</b></p>
     * 
     * @param financingCoeff
     *     Financing Coefficient for Company in Percent
     */
    public void setFinancingCoeff(
        @Nullable
        final BigDecimal financingCoeff) {
        rememberChangedField("BPFinancingCoeffInPercent", this.financingCoeff);
        this.financingCoeff = financingCoeff;
    }

    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>BPEquityRatioInPercent</b></p>
     * 
     * @param equityRatio
     *     Equity Ratio of Company in Percent
     */
    public void setEquityRatio(
        @Nullable
        final BigDecimal equityRatio) {
        rememberChangedField("BPEquityRatioInPercent", this.equityRatio);
        this.equityRatio = equityRatio;
    }

    @Override
    protected String getEntityCollection() {
        return "A_BPFiscalYearInformation";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("BusinessPartner", getBusinessPartner());
        result.put("BusinessPartnerFiscalYear", getFiscalYear());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("BusinessPartner", getBusinessPartner());
        values.put("BusinessPartnerFiscalYear", getFiscalYear());
        values.put("BPBalanceSheetCurrency", getBalSheetCurrency());
        values.put("BPAnnualStockholderMeetingDate", getAnnStckholdMeeting());
        values.put("BPFiscalYearStartDate", getFiscYearStartDate());
        values.put("BPFiscalYearEndDate", getFiscalYearEnd());
        values.put("BPFiscalYearIsClosed", getYearEndClosing());
        values.put("BPFiscalYearClosingDate", getYearEndClosing_2());
        values.put("BPFsclYrCnsldtdFinStatementDte", getConsFinStatements());
        values.put("BPCapitalStockAmtInBalShtCrcy", getCapitalStock());
        values.put("BPIssdStockCptlAmtInBalShtCrcy", getIssuedStockCapital());
        values.put("BPPartcipnCertAmtInBalShtCrcy", getPartCertsOutstand());
        values.put("BPEquityCapitalAmtInBalShtCrcy", getEquityCapital());
        values.put("BPGrossPremiumAmtInBalShtCrcy", getGrossPremium());
        values.put("BPNetPremiumAmtInBalShtCrcy", getNetPremium());
        values.put("BPAnnualSalesAmtInBalShtCrcy", getAnnualSales());
        values.put("BPAnnualNetIncAmtInBalShtCrcy", getAnnualNetIncome());
        values.put("BPDividendDistrAmtInBalShtCrcy", getDividend());
        values.put("BPDebtRatioInYears", getDebtRatio());
        values.put("BPAnnualPnLAmtInBalShtCrcy", getReportedProfit());
        values.put("BPBalSheetTotalAmtInBalShtCrcy", getBalanceSheetTotal());
        values.put("BPNumberOfEmployees", getNumberOfEmployees());
        values.put("BPCptlReserveAmtInBalShtCrcy", getCapitalReserve());
        values.put("BPLglRevnRsrvAmtInBalShtCrcy", getLegalRevenueRes());
        values.put("RevnRsrvOwnStkAmtInBalShtCrcy", getRevReservesOwnSt());
        values.put("BPStatryReserveAmtInBalShtCrcy", getStatutoryReserve());
        values.put("BPOthRevnRsrvAmtInBalShtCrcy", getOtherRevenueRes());
        values.put("BPPnLCarryfwdAmtInBalShtCrcy", getPLCarriedFwd());
        values.put("BPSuborddLbltyAmtInBalShtCrcy", getSubordLiabilities());
        values.put("BPRetOnTotalCptlEmpldInPercent", getReturnOnTotCap());
        values.put("BPDebtClearancePeriodInYears", getDebtClearancePer());
        values.put("BPFinancingCoeffInPercent", getFinancingCoeff());
        values.put("BPEquityRatioInPercent", getEquityRatio());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("BusinessPartner")) {
                final Object value = values.remove("BusinessPartner");
                if ((value == null)||(!value.equals(getBusinessPartner()))) {
                    setBusinessPartner(((String) value));
                }
            }
            if (values.containsKey("BusinessPartnerFiscalYear")) {
                final Object value = values.remove("BusinessPartnerFiscalYear");
                if ((value == null)||(!value.equals(getFiscalYear()))) {
                    setFiscalYear(((String) value));
                }
            }
            if (values.containsKey("BPBalanceSheetCurrency")) {
                final Object value = values.remove("BPBalanceSheetCurrency");
                if ((value == null)||(!value.equals(getBalSheetCurrency()))) {
                    setBalSheetCurrency(((String) value));
                }
            }
            if (values.containsKey("BPAnnualStockholderMeetingDate")) {
                final Object value = values.remove("BPAnnualStockholderMeetingDate");
                if ((value == null)||(!value.equals(getAnnStckholdMeeting()))) {
                    setAnnStckholdMeeting(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BPFiscalYearStartDate")) {
                final Object value = values.remove("BPFiscalYearStartDate");
                if ((value == null)||(!value.equals(getFiscYearStartDate()))) {
                    setFiscYearStartDate(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BPFiscalYearEndDate")) {
                final Object value = values.remove("BPFiscalYearEndDate");
                if ((value == null)||(!value.equals(getFiscalYearEnd()))) {
                    setFiscalYearEnd(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BPFiscalYearIsClosed")) {
                final Object value = values.remove("BPFiscalYearIsClosed");
                if ((value == null)||(!value.equals(getYearEndClosing()))) {
                    setYearEndClosing(((Boolean) value));
                }
            }
            if (values.containsKey("BPFiscalYearClosingDate")) {
                final Object value = values.remove("BPFiscalYearClosingDate");
                if ((value == null)||(!value.equals(getYearEndClosing_2()))) {
                    setYearEndClosing_2(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BPFsclYrCnsldtdFinStatementDte")) {
                final Object value = values.remove("BPFsclYrCnsldtdFinStatementDte");
                if ((value == null)||(!value.equals(getConsFinStatements()))) {
                    setConsFinStatements(((LocalDateTime) value));
                }
            }
            if (values.containsKey("BPCapitalStockAmtInBalShtCrcy")) {
                final Object value = values.remove("BPCapitalStockAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getCapitalStock()))) {
                    setCapitalStock(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPIssdStockCptlAmtInBalShtCrcy")) {
                final Object value = values.remove("BPIssdStockCptlAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getIssuedStockCapital()))) {
                    setIssuedStockCapital(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPPartcipnCertAmtInBalShtCrcy")) {
                final Object value = values.remove("BPPartcipnCertAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getPartCertsOutstand()))) {
                    setPartCertsOutstand(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPEquityCapitalAmtInBalShtCrcy")) {
                final Object value = values.remove("BPEquityCapitalAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getEquityCapital()))) {
                    setEquityCapital(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPGrossPremiumAmtInBalShtCrcy")) {
                final Object value = values.remove("BPGrossPremiumAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getGrossPremium()))) {
                    setGrossPremium(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPNetPremiumAmtInBalShtCrcy")) {
                final Object value = values.remove("BPNetPremiumAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getNetPremium()))) {
                    setNetPremium(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPAnnualSalesAmtInBalShtCrcy")) {
                final Object value = values.remove("BPAnnualSalesAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getAnnualSales()))) {
                    setAnnualSales(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPAnnualNetIncAmtInBalShtCrcy")) {
                final Object value = values.remove("BPAnnualNetIncAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getAnnualNetIncome()))) {
                    setAnnualNetIncome(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPDividendDistrAmtInBalShtCrcy")) {
                final Object value = values.remove("BPDividendDistrAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getDividend()))) {
                    setDividend(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPDebtRatioInYears")) {
                final Object value = values.remove("BPDebtRatioInYears");
                if ((value == null)||(!value.equals(getDebtRatio()))) {
                    setDebtRatio(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPAnnualPnLAmtInBalShtCrcy")) {
                final Object value = values.remove("BPAnnualPnLAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getReportedProfit()))) {
                    setReportedProfit(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPBalSheetTotalAmtInBalShtCrcy")) {
                final Object value = values.remove("BPBalSheetTotalAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getBalanceSheetTotal()))) {
                    setBalanceSheetTotal(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPNumberOfEmployees")) {
                final Object value = values.remove("BPNumberOfEmployees");
                if ((value == null)||(!value.equals(getNumberOfEmployees()))) {
                    setNumberOfEmployees(((String) value));
                }
            }
            if (values.containsKey("BPCptlReserveAmtInBalShtCrcy")) {
                final Object value = values.remove("BPCptlReserveAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getCapitalReserve()))) {
                    setCapitalReserve(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPLglRevnRsrvAmtInBalShtCrcy")) {
                final Object value = values.remove("BPLglRevnRsrvAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getLegalRevenueRes()))) {
                    setLegalRevenueRes(((BigDecimal) value));
                }
            }
            if (values.containsKey("RevnRsrvOwnStkAmtInBalShtCrcy")) {
                final Object value = values.remove("RevnRsrvOwnStkAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getRevReservesOwnSt()))) {
                    setRevReservesOwnSt(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPStatryReserveAmtInBalShtCrcy")) {
                final Object value = values.remove("BPStatryReserveAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getStatutoryReserve()))) {
                    setStatutoryReserve(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPOthRevnRsrvAmtInBalShtCrcy")) {
                final Object value = values.remove("BPOthRevnRsrvAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getOtherRevenueRes()))) {
                    setOtherRevenueRes(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPPnLCarryfwdAmtInBalShtCrcy")) {
                final Object value = values.remove("BPPnLCarryfwdAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getPLCarriedFwd()))) {
                    setPLCarriedFwd(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPSuborddLbltyAmtInBalShtCrcy")) {
                final Object value = values.remove("BPSuborddLbltyAmtInBalShtCrcy");
                if ((value == null)||(!value.equals(getSubordLiabilities()))) {
                    setSubordLiabilities(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPRetOnTotalCptlEmpldInPercent")) {
                final Object value = values.remove("BPRetOnTotalCptlEmpldInPercent");
                if ((value == null)||(!value.equals(getReturnOnTotCap()))) {
                    setReturnOnTotCap(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPDebtClearancePeriodInYears")) {
                final Object value = values.remove("BPDebtClearancePeriodInYears");
                if ((value == null)||(!value.equals(getDebtClearancePer()))) {
                    setDebtClearancePer(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPFinancingCoeffInPercent")) {
                final Object value = values.remove("BPFinancingCoeffInPercent");
                if ((value == null)||(!value.equals(getFinancingCoeff()))) {
                    setFinancingCoeff(((BigDecimal) value));
                }
            }
            if (values.containsKey("BPEquityRatioInPercent")) {
                final Object value = values.remove("BPEquityRatioInPercent");
                if ((value == null)||(!value.equals(getEquityRatio()))) {
                    setEquityRatio(((BigDecimal) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >FiscalYearInformationField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new FiscalYearInformationField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >FiscalYearInformationField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new FiscalYearInformationField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public Destination getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final Destination destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return (com.sap.cloud.sdk.tutorial.datamodel.odata.services.BusinessPartnerService.DEFAULT_SERVICE_PATH);
    }

}
