
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.1.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperUpdate;


/**
 * Fluent helper to update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.SalesAreaTax SalesAreaTax} entity and save it to the S/4HANA system.<p>
 * To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
 * 
 */
public class SalesAreaTaxUpdateFluentHelper
    extends FluentHelperUpdate<SalesAreaTaxUpdateFluentHelper, SalesAreaTax>
{

    /**
     * {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.SalesAreaTax SalesAreaTax} entity object that will be updated in the S/4HANA system.
     * 
     */
    private final SalesAreaTax entity;

    /**
     * Creates a fluent helper object that will update a {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.SalesAreaTax SalesAreaTax} entity on the OData endpoint. To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
     * 
     * @param servicePath
     *     The service path to direct the update requests to.
     * @param entity
     *     The SalesAreaTax to take the updated values from.
     */
    public SalesAreaTaxUpdateFluentHelper(
        @Nonnull
        final String servicePath,
        @Nonnull
        final SalesAreaTax entity,
        @Nonnull
        final String entityCollection) {
        super(servicePath, entityCollection);
        this.entity = entity;
    }

    @Override
    @Nonnull
    protected SalesAreaTax getEntity() {
        return entity;
    }

}
