
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.1.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank Bank}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.BankField BankField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.link.BankLink BankLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#BUSINESS_PARTNER BUSINESS_PARTNER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#BANK_DETAILS_ID BANK_DETAILS_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#BANK_COUNTRY_REGION BANK_COUNTRY_REGION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#BANK_NAME BANK_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#BANK_KEY BANK_KEY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#SWIFTBIC SWIFTBIC}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#BANK_CONTROL_KEY BANK_CONTROL_KEY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#ACCOUNT_HOLDER ACCOUNT_HOLDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#ACCOUNT_NAME ACCOUNT_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#VALID_FROM VALID_FROM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#VALID_TO VALID_TO}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#IBAN IBAN}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#IBAN_VALID_FROM IBAN_VALID_FROM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#BANK_ACCOUNT BANK_ACCOUNT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#REFERENCE_DETAILS REFERENCE_DETAILS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#COLLECTAUTHOR COLLECTAUTHOR}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#CITY CITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.Bank#AUTHORIZATION_GROUP AUTHORIZATION_GROUP}</li>
 * </ul>
 * 
 */
public interface BankSelectable
    extends EntitySelectable<Bank>
{


}
