
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.1.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentTaxInfo;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentTaxInfo CustomerSalesAreaAddressDependentTaxInfo}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.CustomerSalesAreaAddressDependentTaxInfoField CustomerSalesAreaAddressDependentTaxInfoField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.link.CustomerSalesAreaAddressDependentTaxInfoLink CustomerSalesAreaAddressDependentTaxInfoLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentTaxInfo#CUSTOMER CUSTOMER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentTaxInfo#SALES_ORGANIZATION SALES_ORGANIZATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentTaxInfo#REF_DIST_CH_CUST_MAT REF_DIST_CH_CUST_MAT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentTaxInfo#DIVISION DIVISION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentTaxInfo#ADDRESS_NUMBER ADDRESS_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentTaxInfo#DEPARTURE_CTRY_REG DEPARTURE_CTRY_REG}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentTaxInfo#TAX_CONDITION_TYPE TAX_CONDITION_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentTaxInfo#TAX_CLASSIFICATION TAX_CLASSIFICATION}</li>
 * </ul>
 * 
 */
public interface CustomerSalesAreaAddressDependentTaxInfoSelectable
    extends EntitySelectable<CustomerSalesAreaAddressDependentTaxInfo>
{


}
