
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.1.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation CustomerSalesAreaAddressDependentInformation}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.CustomerSalesAreaAddressDependentInformationField CustomerSalesAreaAddressDependentInformationField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.link.CustomerSalesAreaAddressDependentInformationLink CustomerSalesAreaAddressDependentInformationLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#CUSTOMER CUSTOMER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#SALES_ORGANIZATION SALES_ORGANIZATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#DISTRIBUTION_CHANNEL DISTRIBUTION_CHANNEL}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#DIVISION DIVISION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#ADDRESS_NUMBER ADDRESS_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#INCOTERMS INCOTERMS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#INCOTERMS_LOCATION1 INCOTERMS_LOCATION1}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#INCOTERMS_LOCATION2 INCOTERMS_LOCATION2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#LOCATION_UUID LOCATION_UUID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#LOCATION_U_U_I_D_2 LOCATION_U_U_I_D_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#LOCATION_U_U_I_D_3 LOCATION_U_U_I_D_3}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#DEL_BLCK_SALES_AR DEL_BLCK_SALES_AR}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#SALES_OFFICE SALES_OFFICE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#SALES_GROUP SALES_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#SHIPPING_CONDITIONS SHIPPING_CONDITIONS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#DELIVERING_PLANT DELIVERING_PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.CustomerSalesAreaAddressDependentInformation#INCOTERMS_VERSION INCOTERMS_VERSION}</li>
 * </ul>
 * 
 */
public interface CustomerSalesAreaAddressDependentInformationSelectable
    extends EntitySelectable<CustomerSalesAreaAddressDependentInformation>
{


}
